-- Restores advanced CRM tables and columns after an accidental schema removal.
-- This migration intentionally changes only the tips_crm schema.

ALTER TABLE tips_crm.territories
  ADD COLUMN IF NOT EXISTS client_key text;
CREATE UNIQUE INDEX IF NOT EXISTS territories_client_key_unique_idx
  ON tips_crm.territories (client_key) WHERE client_key IS NOT NULL;

ALTER TABLE tips_crm.accounts
  ADD COLUMN IF NOT EXISTS finance_customer_code text;
CREATE UNIQUE INDEX IF NOT EXISTS accounts_finance_customer_code_unique_idx
  ON tips_crm.accounts (finance_customer_code) WHERE finance_customer_code IS NOT NULL;

ALTER TABLE tips_crm.notifications
  ADD COLUMN IF NOT EXISTS territory_id uuid REFERENCES tips_crm.territories(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS captured_at timestamptz;
CREATE INDEX IF NOT EXISTS notifications_territory_capture_idx
  ON tips_crm.notifications (territory_id, captured_at DESC);

ALTER TABLE tips_crm.visits
  ADD COLUMN IF NOT EXISTS follow_up_action text,
  ADD COLUMN IF NOT EXISTS follow_up_on date,
  ADD COLUMN IF NOT EXISTS visit_priority text NOT NULL DEFAULT 'medium',
  ADD COLUMN IF NOT EXISTS collection_amount numeric(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS revenue_amount numeric(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS receipt_reference text,
  ADD COLUMN IF NOT EXISTS medical_interaction_type text,
  ADD COLUMN IF NOT EXISTS medical_visit_goal text,
  ADD COLUMN IF NOT EXISTS promoted_product text,
  ADD COLUMN IF NOT EXISTS scientific_message text,
  ADD COLUMN IF NOT EXISTS doctor_interest text,
  ADD COLUMN IF NOT EXISTS medical_feedback text;
CREATE INDEX IF NOT EXISTS visits_receipt_reference_idx
  ON tips_crm.visits (receipt_reference) WHERE receipt_reference IS NOT NULL;
CREATE INDEX IF NOT EXISTS visits_follow_up_idx
  ON tips_crm.visits (follow_up_on) WHERE follow_up_on IS NOT NULL;

CREATE TABLE IF NOT EXISTS tips_crm.monthly_targets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  month_start date NOT NULL,
  target_type text NOT NULL CHECK (target_type IN ('rep', 'territory')),
  target_key text NOT NULL,
  target_value numeric(14,2) NOT NULL CHECK (target_value >= 0),
  metric text NOT NULL CHECK (metric IN ('visits', 'collection', 'revenue')),
  alert_threshold smallint NOT NULL DEFAULT 70 CHECK (alert_threshold BETWEEN 1 AND 100),
  created_by uuid REFERENCES tips_crm.profiles(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (month_start, target_type, target_key, metric)
);

CREATE TABLE IF NOT EXISTS tips_crm.financial_sync_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initiated_by uuid REFERENCES tips_crm.profiles(id),
  source_type text NOT NULL DEFAULT 'google_sheets',
  status text NOT NULL CHECK (status IN ('success', 'failed')),
  summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tips_crm.visit_attachments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  visit_id uuid NOT NULL REFERENCES tips_crm.visits(id) ON DELETE CASCADE,
  profile_id uuid NOT NULL REFERENCES tips_crm.profiles(id) ON DELETE CASCADE,
  bucket_path text NOT NULL UNIQUE,
  file_name text NOT NULL,
  mime_type text,
  file_size bigint CHECK (file_size IS NULL OR file_size >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tips_crm.medical_materials (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  material_type text NOT NULL CHECK (material_type IN ('sample', 'brochure', 'leaflet', 'other')),
  unit_label text NOT NULL DEFAULT 'وحدة',
  central_quantity numeric(14,2) NOT NULL DEFAULT 0 CHECK (central_quantity >= 0),
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid REFERENCES tips_crm.profiles(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tips_crm.medical_rep_material_stock (
  material_id uuid NOT NULL REFERENCES tips_crm.medical_materials(id) ON DELETE CASCADE,
  rep_id uuid NOT NULL REFERENCES tips_crm.profiles(id) ON DELETE CASCADE,
  quantity numeric(14,2) NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (material_id, rep_id)
);

CREATE TABLE IF NOT EXISTS tips_crm.medical_material_deliveries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  material_id uuid NOT NULL REFERENCES tips_crm.medical_materials(id),
  account_id uuid NOT NULL REFERENCES tips_crm.accounts(id),
  rep_id uuid NOT NULL REFERENCES tips_crm.profiles(id),
  quantity numeric(14,2) NOT NULL CHECK (quantity > 0),
  receipt_confirmed boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tips_crm.medical_monthly_targets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  month_start date NOT NULL,
  target_type text NOT NULL CHECK (target_type IN ('rep', 'area', 'product')),
  target_key text NOT NULL,
  metric text NOT NULL CHECK (metric IN ('interactions', 'in_person', 'high_interest', 'information_requests', 'product_promotions')),
  target_value numeric(14,2) NOT NULL CHECK (target_value >= 0),
  alert_threshold smallint NOT NULL DEFAULT 70 CHECK (alert_threshold BETWEEN 1 AND 100),
  created_by uuid REFERENCES tips_crm.profiles(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (month_start, target_type, target_key, metric)
);

CREATE TABLE IF NOT EXISTS tips_crm.medical_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  topic text NOT NULL,
  focus_product text,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz,
  venue text NOT NULL,
  state text NOT NULL,
  city text NOT NULL,
  notes text,
  assigned_rep_id uuid NOT NULL REFERENCES tips_crm.profiles(id),
  created_by uuid REFERENCES tips_crm.profiles(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (ends_at IS NULL OR ends_at >= starts_at)
);

CREATE TABLE IF NOT EXISTS tips_crm.medical_event_invitations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES tips_crm.medical_events(id) ON DELETE CASCADE,
  account_id uuid NOT NULL REFERENCES tips_crm.accounts(id),
  assigned_rep_id uuid NOT NULL REFERENCES tips_crm.profiles(id),
  invitation_status text NOT NULL DEFAULT 'invited' CHECK (invitation_status IN ('invited', 'confirmed', 'declined', 'attended', 'no_show', 'follow_up')),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (event_id, account_id)
);

CREATE INDEX IF NOT EXISTS medical_event_invitations_rep_idx
  ON tips_crm.medical_event_invitations (assigned_rep_id, created_at DESC);

ALTER TABLE tips_crm.monthly_targets ENABLE ROW LEVEL SECURITY;
ALTER TABLE tips_crm.financial_sync_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE tips_crm.visit_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE tips_crm.medical_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE tips_crm.medical_rep_material_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE tips_crm.medical_material_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE tips_crm.medical_monthly_targets ENABLE ROW LEVEL SECURITY;
ALTER TABLE tips_crm.medical_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE tips_crm.medical_event_invitations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS monthly_targets_read ON tips_crm.monthly_targets;
DROP POLICY IF EXISTS monthly_targets_manage ON tips_crm.monthly_targets;
CREATE POLICY monthly_targets_read ON tips_crm.monthly_targets FOR SELECT TO authenticated
  USING (tips_crm.has_permission('view_team_data') OR tips_crm.has_permission('write_own_plans'));
CREATE POLICY monthly_targets_manage ON tips_crm.monthly_targets FOR ALL TO authenticated
  USING (tips_crm.has_permission('view_team_data')) WITH CHECK (tips_crm.has_permission('view_team_data'));

DROP POLICY IF EXISTS financial_sync_audit_read ON tips_crm.financial_sync_audit;
CREATE POLICY financial_sync_audit_read ON tips_crm.financial_sync_audit FOR SELECT TO authenticated
  USING (tips_crm.has_permission('export_reports'));

DROP POLICY IF EXISTS visit_attachments_read ON tips_crm.visit_attachments;
DROP POLICY IF EXISTS visit_attachments_insert ON tips_crm.visit_attachments;
CREATE POLICY visit_attachments_read ON tips_crm.visit_attachments FOR SELECT TO authenticated
  USING (profile_id = auth.uid() OR tips_crm.has_permission('view_team_data'));
CREATE POLICY visit_attachments_insert ON tips_crm.visit_attachments FOR INSERT TO authenticated
  WITH CHECK (profile_id = auth.uid());

DROP POLICY IF EXISTS medical_materials_read ON tips_crm.medical_materials;
DROP POLICY IF EXISTS medical_materials_manage ON tips_crm.medical_materials;
CREATE POLICY medical_materials_read ON tips_crm.medical_materials FOR SELECT TO authenticated
  USING (is_active AND (tips_crm.has_permission('view_team_data') OR EXISTS (SELECT 1 FROM tips_crm.profiles p WHERE p.id = auth.uid() AND p.role_key = 'medical_rep')));
CREATE POLICY medical_materials_manage ON tips_crm.medical_materials FOR ALL TO authenticated
  USING (tips_crm.has_permission('view_team_data')) WITH CHECK (tips_crm.has_permission('view_team_data'));

DROP POLICY IF EXISTS medical_stock_read ON tips_crm.medical_rep_material_stock;
CREATE POLICY medical_stock_read ON tips_crm.medical_rep_material_stock FOR SELECT TO authenticated
  USING (rep_id = auth.uid() OR tips_crm.has_permission('view_team_data'));

DROP POLICY IF EXISTS medical_deliveries_read ON tips_crm.medical_material_deliveries;
CREATE POLICY medical_deliveries_read ON tips_crm.medical_material_deliveries FOR SELECT TO authenticated
  USING (rep_id = auth.uid() OR tips_crm.has_permission('view_team_data'));

DROP POLICY IF EXISTS medical_targets_read ON tips_crm.medical_monthly_targets;
DROP POLICY IF EXISTS medical_targets_manage ON tips_crm.medical_monthly_targets;
CREATE POLICY medical_targets_read ON tips_crm.medical_monthly_targets FOR SELECT TO authenticated
  USING (tips_crm.has_permission('view_team_data') OR target_type = 'rep' AND target_key = auth.uid()::text);
CREATE POLICY medical_targets_manage ON tips_crm.medical_monthly_targets FOR ALL TO authenticated
  USING (tips_crm.has_permission('view_team_data')) WITH CHECK (tips_crm.has_permission('view_team_data'));

DROP POLICY IF EXISTS medical_events_read ON tips_crm.medical_events;
DROP POLICY IF EXISTS medical_events_manage ON tips_crm.medical_events;
CREATE POLICY medical_events_read ON tips_crm.medical_events FOR SELECT TO authenticated
  USING (assigned_rep_id = auth.uid() OR tips_crm.has_permission('view_team_data'));
CREATE POLICY medical_events_manage ON tips_crm.medical_events FOR ALL TO authenticated
  USING (tips_crm.has_permission('view_team_data')) WITH CHECK (tips_crm.has_permission('view_team_data'));

DROP POLICY IF EXISTS medical_event_invitations_read ON tips_crm.medical_event_invitations;
CREATE POLICY medical_event_invitations_read ON tips_crm.medical_event_invitations FOR SELECT TO authenticated
  USING (assigned_rep_id = auth.uid() OR tips_crm.has_permission('view_team_data'));

CREATE OR REPLACE FUNCTION public.tips_crm_save_visit_report(
  account_uuid uuid,
  visit_status text,
  visit_outcome text,
  visit_notes text,
  follow_up_action_input text DEFAULT NULL,
  follow_up_on_input date DEFAULT NULL,
  visit_priority_input text DEFAULT 'medium',
  latitude numeric DEFAULT NULL,
  longitude numeric DEFAULT NULL,
  accuracy integer DEFAULT NULL,
  collection_amount_input numeric DEFAULT 0,
  revenue_amount_input numeric DEFAULT 0,
  receipt_reference_input text DEFAULT NULL,
  medical_interaction_type_input text DEFAULT NULL,
  medical_visit_goal_input text DEFAULT NULL,
  promoted_product_input text DEFAULT NULL,
  scientific_message_input text DEFAULT NULL,
  doctor_interest_input text DEFAULT NULL,
  medical_feedback_input text DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = tips_crm, auth, public
AS $$
DECLARE saved_id uuid;
BEGIN
  IF auth.uid() IS NULL OR NOT tips_crm.has_permission('write_own_visits') THEN RAISE EXCEPTION 'Visit write permission required'; END IF;
  IF visit_status NOT IN ('completed', 'needs_review') THEN RAISE EXCEPTION 'Invalid visit status'; END IF;
  IF COALESCE(collection_amount_input, 0) < 0 OR COALESCE(revenue_amount_input, 0) < 0 THEN RAISE EXCEPTION 'Financial amounts cannot be negative'; END IF;
  INSERT INTO tips_crm.visits (
    rep_id, account_id, status, outcome, notes, checked_in_at, check_in_latitude, check_in_longitude,
    location_accuracy_meters, follow_up_action, follow_up_on, visit_priority, collection_amount,
    revenue_amount, receipt_reference, medical_interaction_type, medical_visit_goal, promoted_product,
    scientific_message, doctor_interest, medical_feedback
  ) VALUES (
    auth.uid(), account_uuid, visit_status, NULLIF(trim(visit_outcome), ''), NULLIF(trim(visit_notes), ''), now(), latitude, longitude,
    accuracy, NULLIF(trim(follow_up_action_input), ''), follow_up_on_input,
    CASE WHEN visit_priority_input IN ('low', 'medium', 'high') THEN visit_priority_input ELSE 'medium' END,
    COALESCE(collection_amount_input, 0), COALESCE(revenue_amount_input, 0), NULLIF(trim(receipt_reference_input), ''),
    NULLIF(trim(medical_interaction_type_input), ''), NULLIF(trim(medical_visit_goal_input), ''), NULLIF(trim(promoted_product_input), ''),
    NULLIF(trim(scientific_message_input), ''), NULLIF(trim(doctor_interest_input), ''), NULLIF(trim(medical_feedback_input), '')
  ) RETURNING id INTO saved_id;
  PERFORM tips_crm.log_audit('visit_report_saved', 'visit', saved_id::text, jsonb_build_object('account_id', account_uuid, 'status', visit_status));
  RETURN saved_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.tips_crm_medical_material_overview()
RETURNS TABLE(material_id uuid, name text, material_type text, unit_label text, central_quantity numeric, allocated_quantity numeric, delivered_quantity numeric)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = tips_crm, auth, public
AS $$
  SELECT material.id, material.name, material.material_type, material.unit_label, material.central_quantity,
    COALESCE((SELECT sum(stock.quantity) FROM tips_crm.medical_rep_material_stock stock WHERE stock.material_id = material.id), 0),
    COALESCE((SELECT sum(delivery.quantity) FROM tips_crm.medical_material_deliveries delivery WHERE delivery.material_id = material.id), 0)
  FROM tips_crm.medical_materials material
  WHERE tips_crm.has_permission('view_team_data')
  ORDER BY material.name;
$$;

CREATE OR REPLACE FUNCTION public.tips_crm_create_medical_material(material_name text, material_kind text, material_unit text)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = tips_crm, auth, public
AS $$
DECLARE saved_id uuid;
BEGIN
  IF NOT tips_crm.has_permission('view_team_data') THEN RAISE EXCEPTION 'Medical program management permission required'; END IF;
  IF NULLIF(trim(material_name), '') IS NULL OR material_kind NOT IN ('sample', 'brochure', 'leaflet', 'other') THEN RAISE EXCEPTION 'Invalid material details'; END IF;
  INSERT INTO tips_crm.medical_materials(name, material_type, unit_label, created_by)
  VALUES (trim(material_name), material_kind, COALESCE(NULLIF(trim(material_unit), ''), 'وحدة'), auth.uid())
  ON CONFLICT (name) DO UPDATE SET material_type = EXCLUDED.material_type, unit_label = EXCLUDED.unit_label, is_active = true, updated_at = now()
  RETURNING id INTO saved_id;
  PERFORM tips_crm.log_audit('medical_material_saved', 'medical_material', saved_id::text, jsonb_build_object('name', trim(material_name)));
  RETURN saved_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.tips_crm_adjust_medical_material_stock(material_uuid uuid, quantity_change numeric, note text DEFAULT NULL)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = tips_crm, auth, public
AS $$
BEGIN
  IF NOT tips_crm.has_permission('view_team_data') THEN RAISE EXCEPTION 'Medical program management permission required'; END IF;
  UPDATE tips_crm.medical_materials
  SET central_quantity = central_quantity + quantity_change, updated_at = now()
  WHERE id = material_uuid AND central_quantity + quantity_change >= 0;
  IF NOT FOUND THEN RAISE EXCEPTION 'Material not found or resulting stock would be negative'; END IF;
  PERFORM tips_crm.log_audit('medical_material_stock_adjusted', 'medical_material', material_uuid::text, jsonb_build_object('quantity_change', quantity_change, 'note', note));
  RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION public.tips_crm_allocate_medical_material(material_uuid uuid, rep_uuid uuid, allocation_quantity numeric, note text DEFAULT NULL)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = tips_crm, auth, public
AS $$
BEGIN
  IF NOT tips_crm.has_permission('view_team_data') THEN RAISE EXCEPTION 'Medical program management permission required'; END IF;
  IF allocation_quantity <= 0 OR NOT EXISTS (SELECT 1 FROM tips_crm.profiles WHERE id = rep_uuid AND role_key = 'medical_rep' AND is_active) THEN RAISE EXCEPTION 'Invalid allocation'; END IF;
  UPDATE tips_crm.medical_materials SET central_quantity = central_quantity - allocation_quantity, updated_at = now()
  WHERE id = material_uuid AND central_quantity >= allocation_quantity;
  IF NOT FOUND THEN RAISE EXCEPTION 'Insufficient central stock'; END IF;
  INSERT INTO tips_crm.medical_rep_material_stock(material_id, rep_id, quantity, updated_at)
  VALUES (material_uuid, rep_uuid, allocation_quantity, now())
  ON CONFLICT (material_id, rep_id) DO UPDATE SET quantity = tips_crm.medical_rep_material_stock.quantity + EXCLUDED.quantity, updated_at = now();
  PERFORM tips_crm.log_audit('medical_material_allocated', 'medical_material', material_uuid::text, jsonb_build_object('rep_id', rep_uuid, 'quantity', allocation_quantity, 'note', note));
  RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION public.tips_crm_medical_event_overview()
RETURNS TABLE(event_id uuid, title text, topic text, focus_product text, starts_at timestamptz, ends_at timestamptz, venue text, state text, city text, assigned_rep_id uuid, invite_count bigint, confirmed_count bigint, attended_count bigint, follow_up_count bigint)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = tips_crm, auth, public
AS $$
  SELECT event.id, event.title, event.topic, event.focus_product, event.starts_at, event.ends_at, event.venue, event.state, event.city, event.assigned_rep_id,
    count(invitation.id), count(invitation.id) FILTER (WHERE invitation.invitation_status = 'confirmed'),
    count(invitation.id) FILTER (WHERE invitation.invitation_status = 'attended'),
    count(invitation.id) FILTER (WHERE invitation.invitation_status = 'follow_up')
  FROM tips_crm.medical_events event
  LEFT JOIN tips_crm.medical_event_invitations invitation ON invitation.event_id = event.id
  WHERE event.assigned_rep_id = auth.uid() OR tips_crm.has_permission('view_team_data')
  GROUP BY event.id
  ORDER BY event.starts_at DESC;
$$;

CREATE OR REPLACE FUNCTION public.tips_crm_create_medical_event(
  event_title text,
  event_topic text,
  event_product text,
  event_starts_at timestamptz,
  event_ends_at timestamptz,
  event_venue text,
  event_state text,
  event_city text,
  event_notes text,
  doctor_ids uuid[],
  rep_uuid uuid
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = tips_crm, auth, public
AS $$
DECLARE saved_event_id uuid;
BEGIN
  IF NOT tips_crm.has_permission('view_team_data') THEN RAISE EXCEPTION 'Medical program management permission required'; END IF;
  IF NULLIF(trim(event_title), '') IS NULL OR NULLIF(trim(event_topic), '') IS NULL OR NULLIF(trim(event_venue), '') IS NULL THEN RAISE EXCEPTION 'Event details are incomplete'; END IF;
  IF NOT EXISTS (SELECT 1 FROM tips_crm.profiles WHERE id = rep_uuid AND role_key = 'medical_rep' AND is_active) THEN RAISE EXCEPTION 'Assigned representative must be active and medical'; END IF;
  INSERT INTO tips_crm.medical_events(title, topic, focus_product, starts_at, ends_at, venue, state, city, notes, assigned_rep_id, created_by)
  VALUES (trim(event_title), trim(event_topic), NULLIF(trim(event_product), ''), event_starts_at, event_ends_at, trim(event_venue), trim(event_state), trim(event_city), NULLIF(trim(event_notes), ''), rep_uuid, auth.uid())
  RETURNING id INTO saved_event_id;
  INSERT INTO tips_crm.medical_event_invitations(event_id, account_id, assigned_rep_id)
  SELECT saved_event_id, account_id, rep_uuid FROM unnest(COALESCE(doctor_ids, '{}'::uuid[])) account_id
  WHERE EXISTS (SELECT 1 FROM tips_crm.accounts account WHERE account.id = account_id AND account.account_type = 'doctor')
  ON CONFLICT (event_id, account_id) DO NOTHING;
  PERFORM tips_crm.log_audit('medical_event_created', 'medical_event', saved_event_id::text, jsonb_build_object('assigned_rep_id', rep_uuid, 'doctor_count', cardinality(COALESCE(doctor_ids, '{}'::uuid[]))));
  RETURN saved_event_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.tips_crm_update_medical_event_invitation(invitation_uuid uuid, next_status text, note text DEFAULT NULL)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = tips_crm, auth, public
AS $$
BEGIN
  IF next_status NOT IN ('confirmed', 'declined', 'attended', 'no_show', 'follow_up') THEN RAISE EXCEPTION 'Invalid invitation status'; END IF;
  UPDATE tips_crm.medical_event_invitations
  SET invitation_status = next_status, notes = COALESCE(NULLIF(trim(note), ''), notes), updated_at = now()
  WHERE id = invitation_uuid AND (assigned_rep_id = auth.uid() OR tips_crm.has_permission('view_team_data'));
  IF NOT FOUND THEN RAISE EXCEPTION 'Invitation not found or access denied'; END IF;
  PERFORM tips_crm.log_audit('medical_event_invitation_updated', 'medical_event_invitation', invitation_uuid::text, jsonb_build_object('status', next_status));
  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.tips_crm_save_visit_report(uuid, text, text, text, text, date, text, numeric, numeric, integer, numeric, numeric, text, text, text, text, text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_medical_material_overview() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_create_medical_material(text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_adjust_medical_material_stock(uuid, numeric, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_allocate_medical_material(uuid, uuid, numeric, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_medical_event_overview() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_create_medical_event(text, text, text, timestamptz, timestamptz, text, text, text, text, uuid[], uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_update_medical_event_invitation(uuid, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.tips_crm_save_visit_report(uuid, text, text, text, text, date, text, numeric, numeric, integer, numeric, numeric, text, text, text, text, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_medical_material_overview() TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_create_medical_material(text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_adjust_medical_material_stock(uuid, numeric, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_allocate_medical_material(uuid, uuid, numeric, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_medical_event_overview() TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_create_medical_event(text, text, text, timestamptz, timestamptz, text, text, text, text, uuid[], uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_update_medical_event_invitation(uuid, text, text) TO authenticated;
