import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { AdminWebShell } from "@/components/admin-web-shell";
import { palette } from "@/components/crm-ui";
import { exportReportWorkbook, type ExportReportRow } from "@/lib/report-export";
import { supabase } from "@/lib/supabase-client";
import { useSupabaseAuth } from "@/lib/supabase-auth";

type AuditRow = { id: number; action: string; entity_type: string; entity_id: string | null; details: Record<string, unknown>; created_at: string; actor_name: string | null };
const actionMeta: Record<string, { label: string; icon: keyof typeof MaterialIcons.glyphMap; tone: string }> = { invite_created: { label: "إنشاء دعوة", icon: "person-add-alt-1", tone: "#0D9488" }, invite_resent: { label: "إعادة إرسال دعوة", icon: "refresh", tone: "#2563EB" }, invite_revoked: { label: "إلغاء دعوة", icon: "person-remove", tone: "#B63838" }, invite_accepted: { label: "قبول دعوة", icon: "mark-email-read", tone: "#0D9488" }, plan_submitted: { label: "إرسال خطة", icon: "send", tone: "#2563EB" }, plan_approved: { label: "اعتماد خطة", icon: "verified", tone: "#087C61" }, plan_returned: { label: "إعادة خطة", icon: "reply", tone: "#B86D08" }, visit_saved: { label: "توثيق زيارة", icon: "location-on", tone: "#7C3AED" }, account_created: { label: "إضافة جهة", icon: "add-business", tone: "#0D9488" }, account_updated: { label: "تعديل جهة", icon: "edit", tone: "#B45309" }, visit_outcome_saved: { label: "حفظ نتيجة زيارة", icon: "playlist-add-check", tone: "#0D9488" } };

export default function AdminAuditPage() {
  const { session } = useSupabaseAuth();
  const [rows, setRows] = useState<AuditRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState(false);
  const [error, setError] = useState("");
  const load = useCallback(async () => { if (!supabase || !session) return; setLoading(true); const { data, error: requestError } = await supabase.rpc("tips_crm_audit_feed"); if (requestError) setError("لا تملك صلاحية قراءة سجل التدقيق أو لم تتم تهيئة دورك بعد."); else { setRows((data ?? []) as AuditRow[]); setError(""); } setLoading(false); }, [session]);
  useEffect(() => { void load(); }, [load]);
  const exportExcel = async () => {
    if (!supabase || !session) return;
    setExporting(true);
    const { data, error: requestError } = await supabase.rpc("tips_crm_export_report_feed");
    if (requestError) { setExporting(false); Alert.alert("تعذر التصدير", "لا تملك صلاحية تصدير التقارير أو لم تُجهّز البيانات بعد."); return; }
    try { const fileName = await exportReportWorkbook((data ?? []) as ExportReportRow[]); Alert.alert("تم التصدير", `تم إعداد ${fileName} للتنزيل أو المشاركة.`); }
    catch { Alert.alert("تعذر التصدير", "حدث خطأ أثناء إنشاء ملف Excel. أعد المحاولة لاحقاً."); }
    finally { setExporting(false); }
  };
  return <AdminWebShell title="سجل التدقيق"><ScrollView contentContainerStyle={styles.page}><View style={styles.hero}><View style={styles.heroActions}><TouchableOpacity disabled={exporting} onPress={() => void exportExcel()} style={styles.export}><MaterialIcons name="file-download" size={18} color="#143D35" /><Text style={styles.exportText}>{exporting ? "يُجهّز الملف…" : "تصدير Excel"}</Text></TouchableOpacity><TouchableOpacity onPress={() => void load()} style={styles.refresh}><MaterialIcons name="refresh" size={18} color="#FFFFFF" /><Text style={styles.refreshText}>تحديث السجل</Text></TouchableOpacity></View><View style={styles.titleWrap}><Text style={styles.heroTitle}>كل قرار له أثر موثق</Text><Text style={styles.heroCopy}>يتتبع السجل عمليات الدعوات والخطط والزيارات والتعديلات الإدارية داخل Tips CRM.</Text></View></View>{loading ? <View style={styles.state}><ActivityIndicator color={palette.primary} /><Text style={styles.stateText}>يجري تحميل سجل التدقيق…</Text></View> : error ? <View style={styles.state}><MaterialIcons name="lock-outline" size={24} color={palette.warning} /><Text style={styles.stateText}>{error}</Text></View> : rows.length === 0 ? <View style={styles.state}><MaterialIcons name="history" size={24} color={palette.muted} /><Text style={styles.stateText}>لم تُسجّل أي عمليات بعد.</Text></View> : <View style={styles.list}>{rows.map((row) => { const meta = actionMeta[row.action] ?? { label: row.action, icon: "history" as const, tone: palette.muted }; return <View key={row.id} style={styles.row}><View style={[styles.icon, { backgroundColor: `${meta.tone}18` }]}><MaterialIcons name={meta.icon} size={19} color={meta.tone} /></View><View style={styles.rowBody}><View style={styles.rowTop}><Text style={styles.time}>{new Date(row.created_at).toLocaleString("ar")}</Text><Text style={styles.action}>{meta.label}</Text></View><Text style={styles.details}>{row.actor_name ?? "مستخدم النظام"} · {row.entity_type}{row.details?.title ? ` · ${String(row.details.title)}` : row.details?.name ? ` · ${String(row.details.name)}` : ""}</Text></View></View>; })}</View>}</ScrollView></AdminWebShell>;
}

const styles = StyleSheet.create({
  page: { paddingBottom: 30 }, hero: { minHeight: 130, padding: 24, borderRadius: 20, backgroundColor: "#143D35", flexDirection: "row", gap: 20, alignItems: "center", marginBottom: 18 }, heroActions: { gap: 8 }, titleWrap: { flex: 1, alignItems: "flex-end" }, heroTitle: { color: "#FFFFFF", fontSize: 22, fontWeight: "900", textAlign: "right" }, heroCopy: { color: "#C6E6DD", fontSize: 12, lineHeight: 19, textAlign: "right", marginTop: 6 }, refresh: { backgroundColor: "#13A284", paddingHorizontal: 15, minHeight: 42, borderRadius: 12, flexDirection: "row", gap: 6, alignItems: "center", justifyContent: "center" }, refreshText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" }, export: { backgroundColor: "#E7F7F1", paddingHorizontal: 15, minHeight: 42, borderRadius: 12, flexDirection: "row", gap: 6, alignItems: "center", justifyContent: "center" }, exportText: { color: "#143D35", fontSize: 12, fontWeight: "900" }, state: { minHeight: 160, borderRadius: 18, borderWidth: 1, borderColor: "#E2EBE7", backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center", gap: 10 }, stateText: { color: palette.muted, fontSize: 13 }, list: { backgroundColor: "#FFFFFF", borderRadius: 18, borderWidth: 1, borderColor: "#E2EBE7", paddingHorizontal: 17 }, row: { minHeight: 76, flexDirection: "row", gap: 12, alignItems: "center", borderBottomWidth: 1, borderBottomColor: "#EDF2F0" }, icon: { width: 39, height: 39, borderRadius: 13, alignItems: "center", justifyContent: "center" }, rowBody: { flex: 1, alignItems: "flex-end" }, rowTop: { flexDirection: "row", alignSelf: "stretch", justifyContent: "space-between", gap: 10 }, action: { color: palette.ink, fontSize: 13, fontWeight: "900", textAlign: "right" }, time: { color: palette.muted, fontSize: 10 }, details: { color: palette.muted, fontSize: 11, marginTop: 5, textAlign: "right" },
});
