import { AdminWebShell } from "@/components/admin-web-shell";
import { router } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Alert, ScrollView, Share, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useState } from "react";
import { palette } from "@/components/crm-ui";
import { useCrm } from "@/lib/crm-store";
import { useInvitationEmail } from "@/lib/use-invitation-email";

export default function AdminTeamPage() {
  const { data, resendInvite, revokeInvite } = useCrm(); const [busyInviteId, setBusyInviteId] = useState<string | null>(null); const { send: sendInvitationEmail } = useInvitationEmail();
  const resend = async (invite: typeof data.invites[number]) => { setBusyInviteId(invite.id); const updated = await resendInvite(invite); setBusyInviteId(null); if (!updated) { Alert.alert("تعذر إعادة الإرسال", "تحقق من صلاحياتك ثم أعد المحاولة."); return; } try { await sendInvitationEmail(updated.id); Alert.alert("تمت إعادة الإرسال", `أُرسلت الدعوة المحدّثة إلى ${updated.email}.`); } catch { if (updated.acceptUrl) await Share.share({ message: `دعوة Tips CRM المحدثة: ${updated.acceptUrl}` }); Alert.alert("تم إنشاء رابط جديد", "تعذر تسليم البريد آلياً؛ فُتحت نافذة المشاركة لإرسال الرابط يدوياً."); } };
  const revoke = (invite: typeof data.invites[number]) => Alert.alert("إلغاء الدعوة", `هل تريد إلغاء دعوة ${invite.email}؟`, [{ text: "رجوع", style: "cancel" }, { text: "إلغاء", style: "destructive", onPress: async () => { setBusyInviteId(invite.id); const success = await revokeInvite(invite.id); setBusyInviteId(null); Alert.alert(success ? "تم الإلغاء" : "تعذر الإلغاء", success ? "لم يعد الرابط صالحاً." : "حاول مرة أخرى."); } }]);
  return <AdminWebShell title="الفريق والدعوات"><ScrollView contentContainerStyle={styles.page}><View style={styles.hero}><TouchableOpacity onPress={() => router.push("/team" as never)} style={styles.primary}><MaterialIcons name="person-add-alt-1" size={19} color="#FFFFFF" /><Text style={styles.primaryText}>دعوة عضو</Text></TouchableOpacity><View style={{ flex: 1, alignItems: "flex-end" }}><Text style={styles.heroTitle}>إدارة فريق التوزيع</Text><Text style={styles.heroCopy}>راجع الأدوار والمناطق المعيّنة والدعوات المعلقة من بوابة الإدارة.</Text></View></View><Text style={styles.sectionTitle}>الأعضاء النشطون</Text><View style={styles.table}>{data.teamMembers.map((member, index) => <View key={member.id} style={[styles.row, index < data.teamMembers.length - 1 && styles.line]}><TouchableOpacity onPress={() => router.push("/team" as never)} style={styles.edit}><MaterialIcons name="edit" size={17} color={palette.primary} /></TouchableOpacity><Text style={styles.area}>{member.territory}</Text><View style={styles.rolePill}><Text style={styles.roleText}>{member.role}</Text></View><View style={{ flex: 1, alignItems: "flex-end" }}><Text style={styles.memberName}>{member.name}</Text><Text style={styles.memberType}>{member.type}</Text></View><View style={styles.avatar}><Text style={styles.avatarText}>{member.initials}</Text></View></View>)}</View><Text style={styles.sectionTitle}>دعوات الفريق</Text><View style={styles.invites}>{data.invites.map((invite) => <View key={invite.id} style={styles.invite}><View style={styles.inviteTop}><View style={styles.pending}><Text style={styles.pendingText}>{invite.status}</Text></View><View style={{ flex: 1, alignItems: "flex-end" }}><Text style={styles.inviteEmail}>{invite.email}</Text><Text style={styles.inviteMeta}>{invite.role} · {invite.territory} · تنتهي {invite.expiresAt}</Text></View><MaterialIcons name="mail-outline" size={20} color={palette.primary} /></View>{invite.status === "بانتظار الرد" && <View style={styles.inviteActions}><TouchableOpacity disabled={busyInviteId === invite.id} onPress={() => revoke(invite)} style={styles.revoke}><Text style={styles.revokeText}>إلغاء الدعوة</Text></TouchableOpacity><TouchableOpacity disabled={busyInviteId === invite.id} onPress={() => void resend(invite)} style={styles.resend}><MaterialIcons name="refresh" size={16} color="#FFFFFF" /><Text style={styles.resendText}>{busyInviteId === invite.id ? "جارٍ التنفيذ…" : "إعادة الإرسال"}</Text></TouchableOpacity></View>}</View>)}</View></ScrollView></AdminWebShell>;
}
const styles = StyleSheet.create({ page: { paddingBottom: 30 }, hero: { minHeight: 130, padding: 24, borderRadius: 20, backgroundColor: "#143D35", flexDirection: "row", gap: 20, alignItems: "center", marginBottom: 19 }, heroTitle: { color: "#FFFFFF", fontSize: 22, fontWeight: "900", textAlign: "right" }, heroCopy: { color: "#C6E6DD", fontSize: 12, marginTop: 6, textAlign: "right" }, primary: { backgroundColor: "#13A284", paddingHorizontal: 15, minHeight: 42, borderRadius: 12, flexDirection: "row", gap: 6, alignItems: "center", justifyContent: "center" }, primaryText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" }, sectionTitle: { color: palette.ink, fontSize: 16, fontWeight: "900", textAlign: "right", marginBottom: 10, marginTop: 20 }, table: { backgroundColor: "#FFFFFF", borderRadius: 17, borderWidth: 1, borderColor: "#E2EBE7", paddingHorizontal: 17 }, row: { minHeight: 74, flexDirection: "row", alignItems: "center", gap: 16 }, line: { borderBottomWidth: 1, borderBottomColor: "#EDF2F0" }, avatar: { height: 40, width: 40, borderRadius: 13, backgroundColor: "#137F6D", alignItems: "center", justifyContent: "center" }, avatarText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" }, memberName: { color: palette.ink, fontSize: 14, fontWeight: "900", textAlign: "right" }, memberType: { color: palette.muted, fontSize: 10, marginTop: 3, textAlign: "right" }, rolePill: { backgroundColor: "#EAF7F2", paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8 }, roleText: { color: palette.success, fontSize: 10, fontWeight: "800" }, area: { color: palette.muted, width: 170, fontSize: 11, textAlign: "right" }, edit: { width: 34, height: 34, borderRadius: 10, backgroundColor: "#F1F7F5", alignItems: "center", justifyContent: "center" }, invites: { gap: 10 }, invite: { backgroundColor: "#FFFFFF", borderRadius: 15, borderWidth: 1, borderColor: "#E2EBE7", padding: 14 }, inviteTop: { flexDirection: "row", gap: 12, alignItems: "center" }, inviteActions: { flexDirection: "row", gap: 8, marginTop: 12 }, inviteEmail: { color: palette.ink, fontSize: 13, fontWeight: "900", textAlign: "right" }, inviteMeta: { color: palette.muted, fontSize: 10, marginTop: 4, textAlign: "right" }, pending: { backgroundColor: "#FFF6E5", paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8 }, pendingText: { color: palette.warning, fontSize: 10, fontWeight: "800" }, resend: { flex: 1, minHeight: 34, borderRadius: 9, backgroundColor: palette.primary, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5 }, resendText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" }, revoke: { minWidth: 100, minHeight: 34, borderRadius: 9, borderWidth: 1, borderColor: "#F4C9C4", backgroundColor: "#FFF8F7", alignItems: "center", justifyContent: "center" }, revokeText: { color: palette.error, fontSize: 11, fontWeight: "900" } });
