import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useFocusEffect } from "expo-router";
import { useCallback } from "react";
import { FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { AppHeader, palette } from "@/components/crm-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useCrm } from "@/lib/crm-store";

const iconByKind: Record<string, keyof typeof MaterialIcons.glyphMap> = { خطة: "event-note", زيارة: "location-on", تنبيه: "warning-amber", فريق: "groups" };
export default function NotificationsScreen() {
  const { data, markAllNotificationsRead, refreshSharedCatalog } = useCrm();
  useFocusEffect(useCallback(() => { void refreshSharedCatalog(); }, [refreshSharedCatalog]));
  return <ScreenContainer className="px-5" containerClassName="bg-background"><FlatList data={data.notifications} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} ListHeaderComponent={<><AppHeader eyebrow="اعتمادات الخطط وتذكيرات الزيارات" title="التنبيهات" right={<TouchableOpacity onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-forward" size={20} color={palette.primary} /></TouchableOpacity>} /><TouchableOpacity onPress={markAllNotificationsRead} style={styles.readAll}><MaterialIcons name="done-all" size={18} color={palette.primary} /><Text style={styles.readAllText}>تحديد الكل كمقروء</Text></TouchableOpacity></>} renderItem={({ item }) => <View style={[styles.card, !item.readAt && styles.unreadCard]}><View style={[styles.icon, { backgroundColor: item.kind === "تنبيه" ? "#FFF0F0" : "#E9F8F2" }]}><MaterialIcons name={iconByKind[item.kind] ?? "notifications"} size={20} color={item.kind === "تنبيه" ? palette.error : palette.primary} /></View><View style={{ flex: 1, alignItems: "flex-end" }}><View style={styles.cardHead}>{!item.readAt ? <View style={styles.dot} /> : null}<Text style={styles.title}>{item.title}</Text></View><Text style={styles.body}>{item.body}</Text><Text style={styles.time}>{item.time}</Text></View></View>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="notifications-off" size={34} color={palette.muted} /><Text style={styles.emptyText}>لا توجد تنبيهات جديدة.</Text></View>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 10, paddingBottom: 30 }, back: { width: 40, height: 40, borderRadius: 14, backgroundColor: "#E9F8F2", alignItems: "center", justifyContent: "center" }, readAll: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 6, paddingVertical: 8, marginBottom: 12 }, readAllText: { color: palette.primary, fontSize: 12, fontWeight: "800" }, card: { backgroundColor: "#FFFFFF", borderRadius: 18, borderWidth: 1, borderColor: palette.line, padding: 13, flexDirection: "row", gap: 11, marginBottom: 9 }, unreadCard: { borderColor: "#A7D7CB", backgroundColor: "#FCFFFE" }, icon: { width: 39, height: 39, borderRadius: 13, alignItems: "center", justifyContent: "center" }, cardHead: { flexDirection: "row", alignItems: "center", justifyContent: "flex-end", gap: 6, alignSelf: "stretch" }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: palette.teal }, title: { color: palette.ink, fontSize: 14, fontWeight: "800", textAlign: "right" }, body: { color: palette.muted, fontSize: 11, lineHeight: 17, textAlign: "right", marginTop: 4 }, time: { color: palette.primary, fontSize: 10, fontWeight: "700", textAlign: "right", marginTop: 8 }, empty: { alignItems: "center", paddingVertical: 48, gap: 10 }, emptyText: { color: palette.muted, fontSize: 14 } });
