import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { AppHeader, PrimaryButton, StatusBadge, palette } from "@/components/crm-ui";
import { ScreenContainer } from "@/components/screen-container";
import { type AppRole, useCrm } from "@/lib/crm-store";

const roleMeta: Record<AppRole, { label: string; icon: keyof typeof MaterialIcons.glyphMap; tint: string }> = { مدير: { label: "مدير", icon: "admin-panel-settings", tint: "#075E54" }, "مندوب مبيعات": { label: "مندوب مبيعات", icon: "storefront", tint: "#B45309" }, "مندوب طبي": { label: "مندوب طبي", icon: "medical-services", tint: "#2563EB" } };
export default function TeamScreen() {
  const { data, activeMemberId, role, selectTeamMember, updateTeamMemberRole } = useCrm();
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><AppHeader eyebrow="تحديد من يصل إلى الإدارة والتخطيط والزيارات" title="الفريق والصلاحيات" right={<TouchableOpacity onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-forward" size={20} color={palette.primary} /></TouchableOpacity>} /><View style={styles.current}><View style={styles.currentIcon}><MaterialIcons name={roleMeta[role].icon} size={22} color="#FFFFFF" /></View><View style={{ flex: 1, alignItems: "flex-end" }}><Text style={styles.currentLabel}>الحساب النشط حالياً</Text><Text style={styles.currentValue}>{data.teamMembers.find((member) => member.id === activeMemberId)?.name} · {role}</Text></View></View><Text style={styles.note}>اختر أحد الأعضاء لمراجعة ما يراه كل دور داخل التطبيق. المدير فقط يملك الاعتماد، إدارة المناطق، وتعديل نتائج الزيارة.</Text>{data.teamMembers.map((member) => { const selected = member.id === activeMemberId; return <View key={member.id} style={[styles.member, selected && styles.memberSelected]}><TouchableOpacity onPress={() => selectTeamMember(member.id)} style={styles.memberHead}><View style={[styles.avatar, { backgroundColor: roleMeta[member.role].tint }]}><Text style={styles.avatarText}>{member.initials}</Text></View><View style={{ flex: 1, alignItems: "flex-end" }}><View style={styles.memberTitle}><View style={[styles.activeTag, selected && styles.activeTagOn]}><Text style={[styles.activeTagText, selected && styles.activeTagTextOn]}>{selected ? "نشط الآن" : member.territory}</Text></View><Text style={styles.memberName}>{member.name}</Text></View><Text style={styles.memberMeta}>{member.territory} · {member.type}</Text></View></TouchableOpacity><View style={styles.roleRow}>{(["مدير", "مندوب مبيعات", "مندوب طبي"] as AppRole[]).map((item) => <TouchableOpacity key={item} onPress={() => updateTeamMemberRole(member.id, item)} style={[styles.roleChip, member.role === item && styles.roleChipActive]}><Text style={[styles.roleChipText, member.role === item && styles.roleChipTextActive]}>{roleMeta[item].label}</Text></TouchableOpacity>)}</View></View>; })}<PrimaryButton label="العودة إلى لوحة الإدارة" icon="admin-panel-settings" onPress={() => router.replace("/(tabs)/admin" as never)} style={{ marginTop: 10 }} /></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 10, paddingBottom: 30 }, back: { width: 40, height: 40, borderRadius: 14, backgroundColor: "#E9F8F2", alignItems: "center", justifyContent: "center" }, current: { borderRadius: 19, padding: 14, backgroundColor: "#143D35", flexDirection: "row", gap: 10, alignItems: "center" }, currentIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#28715F", alignItems: "center", justifyContent: "center" }, currentLabel: { color: "#CBEDE6", fontSize: 10, textAlign: "right" }, currentValue: { color: "#FFFFFF", fontSize: 14, fontWeight: "800", marginTop: 4, textAlign: "right" }, note: { color: palette.muted, fontSize: 11, lineHeight: 18, textAlign: "right", marginVertical: 15 }, member: { backgroundColor: "#FFFFFF", borderRadius: 18, borderWidth: 1, borderColor: palette.line, padding: 13, marginBottom: 10 }, memberSelected: { borderColor: "#9DD3C4", backgroundColor: "#FAFFFD" }, memberHead: { flexDirection: "row", alignItems: "center", gap: 10 }, avatar: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, avatarText: { color: "#FFFFFF", fontWeight: "800", fontSize: 12 }, memberTitle: { alignSelf: "stretch", flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, memberName: { color: palette.ink, fontSize: 14, fontWeight: "800", textAlign: "right" }, memberMeta: { color: palette.muted, fontSize: 10, marginTop: 3, textAlign: "right" }, activeTag: { paddingVertical: 4, paddingHorizontal: 7, borderRadius: 8, backgroundColor: "#F1F4F2" }, activeTagOn: { backgroundColor: "#E9F8F2" }, activeTagText: { color: palette.muted, fontSize: 9, fontWeight: "700" }, activeTagTextOn: { color: palette.success }, roleRow: { flexDirection: "row-reverse", gap: 6, marginTop: 13, paddingTop: 12, borderTopWidth: 1, borderTopColor: "#EDF1EF" }, roleChip: { flex: 1, borderRadius: 10, borderColor: palette.line, borderWidth: 1, alignItems: "center", paddingVertical: 8 }, roleChipActive: { backgroundColor: "#E9F8F2", borderColor: "#9DD3C4" }, roleChipText: { color: palette.muted, fontSize: 10, fontWeight: "700" }, roleChipTextActive: { color: palette.primary } });
