import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { AppHeader, PrimaryButton, palette } from "@/components/crm-ui";
import { ScreenContainer } from "@/components/screen-container";
import { type TerritoryBoundary, useCrm } from "@/lib/crm-store";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/hooks/use-auth";

export default function TerritoriesScreen() {
  const { data, updateBoundary } = useCrm(); const { isAuthenticated } = useAuth(); const saveMutation = trpc.territories.saveBoundary.useMutation(); const [selectedId, setSelectedId] = useState(data.boundaries[0]?.territoryId ?? "t1"); const boundary = data.boundaries.find((item) => item.territoryId === selectedId) ?? data.boundaries[0]; const [lat, setLat] = useState(boundary?.centerLatitude ?? "15.5581"); const [lng, setLng] = useState(boundary?.centerLongitude ?? "32.5372"); const [radius, setRadius] = useState(String(boundary?.radiusMeters ?? 4000)); const [notes, setNotes] = useState(boundary?.notes ?? "");
  const choose = (item: TerritoryBoundary) => { setSelectedId(item.territoryId); setLat(item.centerLatitude); setLng(item.centerLongitude); setRadius(String(item.radiusMeters)); setNotes(item.notes ?? ""); };
  const save = () => { const radiusMeters = Number(radius); if (!/^-?\d+(\.\d+)?$/.test(lat) || !/^-?\d+(\.\d+)?$/.test(lng) || !Number.isFinite(radiusMeters) || radiusMeters <= 0) { Alert.alert("بيانات غير صحيحة", "أدخل إحداثيات رقمية ونطاقاً موجباً بالمتر."); return; } if (!boundary) return; const next: TerritoryBoundary = { ...boundary, centerLatitude: lat, centerLongitude: lng, radiusMeters, notes, updatedAt: "الآن" }; updateBoundary(next); if (isAuthenticated) saveMutation.mutate({ territoryId: next.territoryId, name: next.name, state: next.state, city: next.city, centerLatitude: next.centerLatitude, centerLongitude: next.centerLongitude, radiusMeters: next.radiusMeters, boundaryNotes: next.notes }); Alert.alert("تم حفظ الحد", `سيُراجع حضور المندوب ضمن نطاق ${radiusMeters} متر حول مركز المنطقة.`); };
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><AppHeader eyebrow="حدد مركز المنطقة ونطاق الزيارة المسموح" title="حدود مناطق التغطية" right={<TouchableOpacity onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-forward" size={20} color={palette.primary} /></TouchableOpacity>} /><View style={styles.info}><MaterialIcons name="my-location" size={19} color={palette.info} /><Text style={styles.infoText}>هذه الحدود تستخدم لمراجعة الزيارة ميدانياً. عدّل الإحداثيات والنطاق بعد التأكد من موقع المنطقة مع الفريق.</Text></View><Text style={styles.sectionTitle}>اختر المنطقة</Text><View style={styles.territoryChoices}>{data.boundaries.map((item) => <TouchableOpacity key={item.territoryId} onPress={() => choose(item)} style={[styles.choice, selectedId === item.territoryId && styles.choiceActive]}><Text style={[styles.choiceText, selectedId === item.territoryId && styles.choiceTextActive]}>{item.name}</Text><Text style={styles.choiceMeta}>{item.city}</Text></TouchableOpacity>)}</View>{boundary ? <View style={styles.form}><Text style={styles.boundaryName}>{boundary.name}</Text><Text style={styles.boundaryMeta}>{boundary.state} · {boundary.city}</Text><Field label="خط العرض Latitude" value={lat} onChangeText={setLat} keyboardType="decimal-pad" /><Field label="خط الطول Longitude" value={lng} onChangeText={setLng} keyboardType="decimal-pad" /><Field label="نطاق المنطقة بالمتر" value={radius} onChangeText={setRadius} keyboardType="number-pad" /><Text style={styles.label}>ملاحظة تشغيلية</Text><TextInput value={notes} onChangeText={setNotes} placeholder="مثال: يشمل المستشفى والعيادات المحيطة" placeholderTextColor="#93A099" textAlign="right" multiline style={styles.notes} /><View style={styles.radiusPreview}><MaterialIcons name="radio-button-checked" size={18} color={palette.primary} /><Text style={styles.radiusText}>نطاق التحقق الحالي: {radius || "0"} متر حول نقطة المنطقة.</Text></View><PrimaryButton label="حفظ حدود المنطقة" icon="save" onPress={save} style={{ marginTop: 16 }} /></View> : null}</ScrollView></ScreenContainer>;
}
function Field({ label, value, onChangeText, keyboardType }: { label: string; value: string; onChangeText: (value: string) => void; keyboardType: "decimal-pad" | "number-pad" }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} textAlign="right" keyboardType={keyboardType} style={styles.input} /></View>; }
const styles = StyleSheet.create({ content: { paddingTop: 10, paddingBottom: 30 }, back: { width: 40, height: 40, borderRadius: 14, backgroundColor: "#E9F8F2", alignItems: "center", justifyContent: "center" }, info: { flexDirection: "row", gap: 8, padding: 12, borderRadius: 15, backgroundColor: "#EFF6FF", alignItems: "flex-start" }, infoText: { color: "#285A8E", fontSize: 11, lineHeight: 17, flex: 1, textAlign: "right" }, sectionTitle: { color: palette.ink, fontSize: 15, fontWeight: "800", textAlign: "right", marginTop: 20, marginBottom: 9 }, territoryChoices: { flexDirection: "row-reverse", gap: 8 }, choice: { flex: 1, borderWidth: 1, borderColor: palette.line, borderRadius: 14, padding: 11, backgroundColor: "#FFFFFF", alignItems: "flex-end" }, choiceActive: { backgroundColor: "#E9F8F2", borderColor: "#9DD3C4" }, choiceText: { color: palette.ink, fontSize: 12, fontWeight: "800", textAlign: "right" }, choiceTextActive: { color: palette.primary }, choiceMeta: { color: palette.muted, fontSize: 10, marginTop: 3 }, form: { marginTop: 15, padding: 15, borderRadius: 19, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: palette.line }, boundaryName: { color: palette.ink, fontSize: 17, fontWeight: "800", textAlign: "right" }, boundaryMeta: { color: palette.muted, fontSize: 11, marginTop: 4, textAlign: "right" }, field: { marginTop: 16 }, label: { color: palette.ink, fontWeight: "800", fontSize: 12, textAlign: "right", marginBottom: 7 }, input: { minHeight: 45, borderWidth: 1, borderColor: palette.line, borderRadius: 12, paddingHorizontal: 12, color: palette.ink, fontSize: 13 }, notes: { minHeight: 82, borderWidth: 1, borderColor: palette.line, borderRadius: 12, padding: 12, color: palette.ink, fontSize: 13, textAlignVertical: "top" }, radiusPreview: { marginTop: 14, padding: 11, borderRadius: 13, backgroundColor: "#E9F8F2", flexDirection: "row", gap: 7, alignItems: "center" }, radiusText: { color: palette.success, fontSize: 11, fontWeight: "700", flex: 1, textAlign: "right" } });

