import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Redirect, router } from "expo-router";
import { AppHeader, PrimaryButton, palette } from "@/components/crm-ui";
import { ScreenContainer } from "@/components/screen-container";
import { getApiBaseUrl } from "@/constants/oauth";
import { useSupabaseAuth } from "@/lib/supabase-auth";

const DAYS = [{ key: "saturday", label: "السبت" }, { key: "sunday", label: "الأحد" }, { key: "monday", label: "الاثنين" }, { key: "tuesday", label: "الثلاثاء" }, { key: "wednesday", label: "الأربعاء" }, { key: "thursday", label: "الخميس" }, { key: "friday", label: "الجمعة" }];

type Setup = { companyId: string; companyName: string; legalName: string; activityType: string; businessPhone: string; supportEmail: string; timezone: string; workingDays: string[]; workdayStartsAt: string; workdayEndsAt: string; gpsTrackingRequired: boolean; outsideVisitTracking: boolean; geofenceEnforcement: boolean; isSetupComplete: boolean; completedAt: string | null; territoryCount: number; teamMemberCount: number; accountCount: number };

const fallback: Setup = { companyId: "", companyName: "", legalName: "", activityType: "", businessPhone: "", supportEmail: "", timezone: "Africa/Khartoum", workingDays: ["saturday", "sunday", "monday", "tuesday", "wednesday", "thursday"], workdayStartsAt: "08:00", workdayEndsAt: "17:00", gpsTrackingRequired: true, outsideVisitTracking: false, geofenceEnforcement: true, isSetupComplete: false, completedAt: null, territoryCount: 0, teamMemberCount: 0, accountCount: 0 };

function setupUrl() { return `${getApiBaseUrl()}/api/company/setup`; }

export default function CompanySetupScreen() {
  const { session, profile } = useSupabaseAuth();
  const [setup, setSetup] = useState<Setup>(fallback);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const isManager = profile?.role_key === "company_manager" || profile?.role_key === "sales_manager" || (profile?.role_key === "system_admin" && !profile.is_platform_admin);

  const request = useCallback(async (method: "GET" | "PUT", body?: Setup) => {
    if (!session?.access_token) throw new Error("انتهت الجلسة. سجّل الدخول مرة أخرى.");
    const response = await fetch(setupUrl(), { method, headers: { Authorization: `Bearer ${session.access_token}`, ...(method === "PUT" ? { "Content-Type": "application/json" } : {}) }, ...(method === "PUT" ? { body: JSON.stringify(body) } : {}) });
    const payload = await response.json().catch(() => ({})) as { setup?: Setup; message?: string };
    if (!response.ok || !payload.setup) throw new Error(payload.message || "تعذر الاتصال بإعدادات الشركة.");
    return payload.setup;
  }, [session?.access_token]);

  useEffect(() => { if (!session || !isManager) return; void (async () => { try { setLoading(true); setError(null); setSetup(await request("GET")); } catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر تحميل الإعدادات."); } finally { setLoading(false); } })(); }, [isManager, request, session]);

  const basicCompleted = useMemo(() => [setup.companyName.trim().length > 1, setup.activityType.trim().length > 1, setup.workingDays.length > 0, Boolean(setup.workdayStartsAt && setup.workdayEndsAt)].filter(Boolean).length, [setup]);
  const toggleDay = (day: string) => setSetup((current) => ({ ...current, workingDays: current.workingDays.includes(day) ? current.workingDays.filter((item) => item !== day) : [...current.workingDays, day] }));
  const save = async () => { try { setSaving(true); setError(null); const saved = await request("PUT", setup); setSetup(saved); setSuccess("تم حفظ إعدادات الشركة وأصبحت جاهزة لبدء التشغيل."); } catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر حفظ الإعدادات."); } finally { setSaving(false); } };

  if (!session) return <Redirect href="/login" />;
  if (!isManager) return <Redirect href="/company" />;
  if (loading) return <ScreenContainer className="items-center justify-center"><ActivityIndicator color={palette.primary} size="large" /><Text style={styles.loading}>جاري تجهيز ملف الشركة…</Text></ScreenContainer>;

  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
    <AppHeader eyebrow="إعداد أولي · مدير الشركة" title="تهيئة الشركة" right={<TouchableOpacity onPress={() => router.replace("/company" as never)} style={styles.back}><MaterialIcons name="arrow-forward" size={20} color={palette.primary} /></TouchableOpacity>} />
    <View style={styles.hero}><View style={styles.heroIcon}><MaterialIcons name="rocket-launch" size={26} color="#FFFFFF" /></View><View style={styles.heroCopy}><Text style={styles.heroTitle}>{setup.isSetupComplete ? "إعدادات التشغيل جاهزة" : "جهّز شركتك قبل التشغيل"}</Text><Text style={styles.heroText}>حدّد هوية الشركة والدوام وسياسة الموقع مرة واحدة. تستطيع تعديلها لاحقاً من نفس الصفحة.</Text></View></View>
    <View style={styles.progressCard}><View style={styles.progressHead}><Text style={styles.progressValue}>{basicCompleted}/4</Text><View><Text style={styles.progressTitle}>التهيئة الأساسية</Text><Text style={styles.progressText}>{setup.isSetupComplete ? "اكتملت الإعدادات التشغيلية" : "أكمل الحقول المطلوبة للحفظ"}</Text></View></View><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${basicCompleted * 25}%` }]} /></View></View>
    {success ? <Feedback tone="success" text={success} /> : null}{error ? <Feedback tone="error" text={error} /> : null}
    <Section icon="business" title="هوية الشركة" copy="هذه البيانات تظهر لمدير الشركة وتبقى منفصلة عن الشركات الأخرى." />
    <Field label="اسم الشركة التشغيلي" value={setup.companyName} onChangeText={(companyName) => setSetup((current) => ({ ...current, companyName }))} placeholder="مثال: Tips للتوزيع" required />
    <Field label="الاسم القانوني (اختياري)" value={setup.legalName} onChangeText={(legalName) => setSetup((current) => ({ ...current, legalName }))} placeholder="إن كان مختلفاً عن الاسم التشغيلي" />
    <Field label="طبيعة النشاط" value={setup.activityType} onChangeText={(activityType) => setSetup((current) => ({ ...current, activityType }))} placeholder="مثال: توزيع أدوية ومنتجات صحية" required />
    <Field label="هاتف العمل (اختياري)" value={setup.businessPhone} onChangeText={(businessPhone) => setSetup((current) => ({ ...current, businessPhone }))} placeholder="249..." keyboardType="phone-pad" />
    <Field label="بريد الدعم أو الإدارة (اختياري)" value={setup.supportEmail} onChangeText={(supportEmail) => setSetup((current) => ({ ...current, supportEmail }))} placeholder="support@company.sd" keyboardType="email-address" autoCapitalize="none" />
    <Section icon="schedule" title="ساعات العمل" copy="تستخدم لاحقاً لتوضيح الدوام والتنبيهات التشغيلية للفريق." />
    <Text style={styles.label}>أيام العمل <Text style={styles.required}>*</Text></Text><View style={styles.days}>{DAYS.map((day) => <TouchableOpacity key={day.key} onPress={() => toggleDay(day.key)} style={[styles.day, setup.workingDays.includes(day.key) && styles.daySelected]}><Text style={[styles.dayText, setup.workingDays.includes(day.key) && styles.dayTextSelected]}>{day.label}</Text></TouchableOpacity>)}</View>
    <View style={styles.timeRow}><View style={styles.timeField}><Field label="نهاية الدوام" value={setup.workdayEndsAt} onChangeText={(workdayEndsAt) => setSetup((current) => ({ ...current, workdayEndsAt }))} placeholder="17:00" required /></View><View style={styles.timeField}><Field label="بداية الدوام" value={setup.workdayStartsAt} onChangeText={(workdayStartsAt) => setSetup((current) => ({ ...current, workdayStartsAt }))} placeholder="08:00" required /></View></View>
    <Section icon="my-location" title="سياسة الموقع" copy="هذه السياسة تخص شركتك فقط وتُطبق ضمن المهام والزيارات حسب أدوار الفريق." />
    <PolicyRow icon="location-searching" title="يتطلب الموقع عند الزيارة" copy="تأكيد موقع المندوب عند تسجيل الزيارة." value={setup.gpsTrackingRequired} onValueChange={(gpsTrackingRequired) => setSetup((current) => ({ ...current, gpsTrackingRequired }))} />
    <PolicyRow icon="directions-run" title="تتبع خارج الزيارة" copy="تسجيل الموقع أثناء الدوام عندما يتم تشغيل التتبع المباشر." value={setup.outsideVisitTracking} onValueChange={(outsideVisitTracking) => setSetup((current) => ({ ...current, outsideVisitTracking }))} />
    <PolicyRow icon="fence" title="تنبيه حدود المنطقة" copy="تنبيه الإدارة عند الخروج من مناطق التغطية المعيّنة." value={setup.geofenceEnforcement} onValueChange={(geofenceEnforcement) => setSetup((current) => ({ ...current, geofenceEnforcement }))} />
    <View style={styles.readiness}><View style={styles.readinessIcon}><MaterialIcons name="fact-check" size={20} color={palette.primary} /></View><View style={styles.heroCopy}><Text style={styles.readinessTitle}>ما بعد التهيئة الأساسية</Text><Text style={styles.readinessText}>المناطق: {setup.territoryCount} · أعضاء الفريق: {setup.teamMemberCount} · الجهات: {setup.accountCount}</Text><Text style={styles.readinessHint}>الخطوة التالية: أضف مشرفي المبيعات والمشرفين الطبيين والمحاسب، ثم أكمل إعداد المناطق.</Text></View></View>
    <PrimaryButton label={saving ? "جاري حفظ الإعدادات…" : "حفظ وإكمال التهيئة"} icon={saving ? "hourglass-top" : "task-alt"} disabled={saving} onPress={() => void save()} style={{ marginTop: 24 }} />
    {setup.isSetupComplete ? <PrimaryButton label="إعداد فريق الشركة" icon="groups" onPress={() => router.push("/company-team-setup" as never)} style={{ marginTop: 10 }} /> : null}
    <TouchableOpacity onPress={() => router.replace("/company" as never)} style={styles.later}><Text style={styles.laterText}>العودة إلى لوحة الشركة</Text></TouchableOpacity>
  </ScrollView></ScreenContainer>;
}

function Section({ icon, title, copy }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; copy: string }) { return <View style={styles.section}><View style={styles.sectionIcon}><MaterialIcons name={icon} size={19} color={palette.primary} /></View><View style={styles.heroCopy}><Text style={styles.sectionTitle}>{title}</Text><Text style={styles.sectionCopy}>{copy}</Text></View></View>; }
function Field({ label, value, onChangeText, placeholder, required, keyboardType, autoCapitalize }: { label: string; value: string; onChangeText: (value: string) => void; placeholder: string; required?: boolean; keyboardType?: "default" | "phone-pad" | "email-address"; autoCapitalize?: "none" | "sentences" | "words" | "characters" }) { return <View style={styles.field}><Text style={styles.label}>{label}{required ? <Text style={styles.required}> *</Text> : null}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#94A39C" textAlign="right" keyboardType={keyboardType} autoCapitalize={autoCapitalize} style={styles.input} /></View>; }
function PolicyRow({ icon, title, copy, value, onValueChange }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; copy: string; value: boolean; onValueChange: (value: boolean) => void }) { return <View style={styles.policy}><Switch value={value} onValueChange={onValueChange} trackColor={{ false: "#D6E0DC", true: "#73B7A6" }} thumbColor="#FFFFFF" /><View style={styles.policyIcon}><MaterialIcons name={icon} size={18} color={palette.primary} /></View><View style={styles.heroCopy}><Text style={styles.policyTitle}>{title}</Text><Text style={styles.policyCopy}>{copy}</Text></View></View>; }
function Feedback({ tone, text }: { tone: "success" | "error"; text: string }) { const success = tone === "success"; return <View style={[styles.feedback, success ? styles.feedbackSuccess : styles.feedbackError]}><MaterialIcons name={success ? "check-circle" : "error-outline"} size={18} color={success ? palette.success : palette.error} /><Text style={[styles.feedbackText, { color: success ? palette.success : palette.error }]}>{text}</Text></View>; }

const styles = StyleSheet.create({
  content: { paddingTop: 10, paddingBottom: 34, maxWidth: 620, width: "100%", alignSelf: "center" }, loading: { color: palette.muted, fontSize: 13, marginTop: 12 }, back: { width: 39, height: 39, borderRadius: 13, backgroundColor: "#E9F8F2", alignItems: "center", justifyContent: "center" }, hero: { flexDirection: "row-reverse", gap: 12, alignItems: "center", backgroundColor: "#143D35", borderRadius: 21, padding: 17 }, heroIcon: { width: 48, height: 48, borderRadius: 16, backgroundColor: "#28715F", alignItems: "center", justifyContent: "center" }, heroCopy: { flex: 1, alignItems: "flex-end" }, heroTitle: { color: "#FFFFFF", fontSize: 16, fontWeight: "900", textAlign: "right" }, heroText: { color: "#C6E6DD", fontSize: 11, lineHeight: 17, marginTop: 4, textAlign: "right" },
  progressCard: { backgroundColor: "#FFFFFF", borderRadius: 17, borderWidth: 1, borderColor: "#CDE5DC", padding: 14, marginTop: 14 }, progressHead: { flexDirection: "row-reverse", alignItems: "center", gap: 10 }, progressValue: { color: palette.primary, fontSize: 18, fontWeight: "900", backgroundColor: "#E9F8F2", paddingHorizontal: 11, paddingVertical: 7, borderRadius: 11 }, progressTitle: { color: palette.ink, fontSize: 13, fontWeight: "900", textAlign: "right" }, progressText: { color: palette.muted, fontSize: 10, marginTop: 3, textAlign: "right" }, progressTrack: { height: 6, borderRadius: 4, backgroundColor: "#EAF0ED", overflow: "hidden", marginTop: 12 }, progressFill: { height: "100%", borderRadius: 4, backgroundColor: palette.primary },
  feedback: { flexDirection: "row-reverse", alignItems: "center", gap: 7, padding: 11, borderRadius: 13, marginTop: 12, borderWidth: 1 }, feedbackSuccess: { backgroundColor: "#E9F8F2", borderColor: "#B9DED3" }, feedbackError: { backgroundColor: "#FFF0F0", borderColor: "#F2C1C1" }, feedbackText: { fontSize: 12, fontWeight: "700", flex: 1, textAlign: "right", lineHeight: 17 },
  section: { flexDirection: "row-reverse", alignItems: "center", gap: 9, marginTop: 23 }, sectionIcon: { width: 34, height: 34, borderRadius: 11, backgroundColor: "#E9F8F2", alignItems: "center", justifyContent: "center" }, sectionTitle: { color: palette.ink, fontSize: 15, fontWeight: "900", textAlign: "right" }, sectionCopy: { color: palette.muted, fontSize: 10, lineHeight: 15, marginTop: 2, textAlign: "right" }, field: { marginTop: 11 }, label: { color: palette.ink, fontSize: 11, fontWeight: "900", textAlign: "right", marginBottom: 6 }, required: { color: palette.error }, input: { minHeight: 48, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#DCE8E3", borderRadius: 13, paddingHorizontal: 12, color: palette.ink, fontSize: 13 },
  days: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 7 }, day: { minHeight: 37, borderRadius: 11, borderWidth: 1, borderColor: "#DCE8E3", paddingHorizontal: 11, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF" }, daySelected: { borderColor: "#7ABCA9", backgroundColor: "#E9F8F2" }, dayText: { color: palette.muted, fontSize: 11, fontWeight: "800" }, dayTextSelected: { color: palette.primary }, timeRow: { flexDirection: "row-reverse", gap: 10 }, timeField: { flex: 1 },
  policy: { flexDirection: "row-reverse", alignItems: "center", gap: 9, backgroundColor: "#FFFFFF", borderRadius: 15, borderWidth: 1, borderColor: palette.line, padding: 12, marginTop: 9 }, policyIcon: { width: 34, height: 34, borderRadius: 11, backgroundColor: "#E9F8F2", alignItems: "center", justifyContent: "center" }, policyTitle: { color: palette.ink, fontSize: 12, fontWeight: "900", textAlign: "right" }, policyCopy: { color: palette.muted, fontSize: 10, lineHeight: 15, marginTop: 2, textAlign: "right" },
  readiness: { flexDirection: "row-reverse", alignItems: "flex-start", gap: 9, backgroundColor: "#EAF4FA", borderRadius: 16, padding: 13, marginTop: 20 }, readinessIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: "#D9EBF6", alignItems: "center", justifyContent: "center" }, readinessTitle: { color: palette.primary, fontSize: 12, fontWeight: "900", textAlign: "right" }, readinessText: { color: palette.ink, fontSize: 10, fontWeight: "800", marginTop: 4, textAlign: "right" }, readinessHint: { color: palette.muted, fontSize: 10, lineHeight: 15, marginTop: 4, textAlign: "right" }, later: { minHeight: 43, justifyContent: "center", alignItems: "center", marginTop: 8 }, laterText: { color: palette.muted, fontSize: 12, fontWeight: "800" },
});
