import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import * as Linking from "expo-linking";
import { useState } from "react";
import { ActivityIndicator, Alert, Platform, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { palette } from "@/components/crm-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useSupabaseAuth } from "@/lib/supabase-auth";
import { isSupabaseConfigured, supabase } from "@/lib/supabase-client";

export default function LoginScreen() {
  const { session, profile, loading, refreshProfile, claimFirstSystemAdmin } = useSupabaseAuth(); const { token } = useLocalSearchParams<{ token?: string }>();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [fullName, setFullName] = useState(""); const [isCreating, setCreating] = useState(false); const [submitting, setSubmitting] = useState(false); const [resetting, setResetting] = useState(false);
  const submit = async () => { if (!supabase || !email.trim() || !password) return; setSubmitting(true); try { if (isCreating) { const { error } = await supabase.auth.signUp({ email: email.trim(), password, options: { data: { full_name: fullName.trim() || "موظف Tips" } } }); if (error) throw error; Alert.alert("تحقق من البريد", "أرسلنا رابط تأكيد إلى بريدك. بعد التأكيد، سجّل الدخول من هذه الشاشة."); setCreating(false); } else { const { error } = await supabase.auth.signInWithPassword({ email: email.trim(), password }); if (error) throw error; await refreshProfile(); router.replace(Platform.OS === "web" ? "/admin" as never : "/(tabs)" as never); } } catch (error) { Alert.alert("تعذر المتابعة", error instanceof Error ? error.message : "تحقق من بيانات الدخول ثم أعد المحاولة."); } finally { setSubmitting(false); } };
  const requestPasswordReset = async () => { if (!supabase || !email.trim()) { Alert.alert("أدخل البريد", "اكتب بريدك الإلكتروني أولاً ثم اضغط استعادة كلمة المرور."); return; } setResetting(true); try { const { error } = await supabase.auth.resetPasswordForEmail(email.trim(), { redirectTo: Linking.createURL("reset-password") }); if (error) throw error; Alert.alert("راجع بريدك", "إذا كان البريد مسجلاً، ستصلك رسالة آمنة لإعادة تعيين كلمة المرور."); } catch (error) { Alert.alert("تعذر إرسال الرابط", error instanceof Error ? error.message : "حاول مرة أخرى لاحقاً."); } finally { setResetting(false); } };
  if (loading) return <ScreenContainer className="items-center justify-center"><ActivityIndicator color={palette.primary} /></ScreenContainer>;
  const claimAdmin = async () => { const success = await claimFirstSystemAdmin(); if (success) Alert.alert("تمت التهيئة", "أصبح حسابك مدير النظام الأول. يمكنك الآن الدخول إلى بوابة الإدارة."); else Alert.alert("تعذر التهيئة", "يوجد مدير نظام بالفعل أو لم يكتمل تجهيز ملفك بعد."); };
  if (session) return <ScreenContainer className="items-center justify-center px-6"><View style={styles.card}><View style={styles.mark}><Text style={styles.markText}>T</Text></View><Text style={styles.title}>تم تسجيل الدخول</Text><Text style={styles.copy}>{profile ? `مرحباً ${profile.full_name}.` : "يجري تجهيز ملفك الوظيفي."}</Text>{profile?.role_key === "sales_rep" ? <TouchableOpacity onPress={claimAdmin} style={styles.claim}><Text style={styles.claimText}>تهيئة هذا الحساب كمدير النظام الأول</Text></TouchableOpacity> : null}{token ? <TouchableOpacity onPress={() => router.replace(`/invite?token=${token}` as never)} style={styles.claim}><Text style={styles.claimText}>متابعة قبول الدعوة</Text></TouchableOpacity> : null}<TouchableOpacity onPress={() => router.replace(Platform.OS === "web" ? "/admin" as never : "/(tabs)" as never)} style={styles.button}><Text style={styles.buttonText}>الانتقال إلى حسابي</Text></TouchableOpacity></View></ScreenContainer>;
  return <ScreenContainer className="px-5" containerClassName="bg-background"><View style={styles.wrap}><View style={styles.hero}><View style={styles.mark}><Text style={styles.markText}>T</Text></View><Text style={styles.title}>Tips CRM</Text><Text style={styles.copy}>{isCreating ? "أنشئ حساب الموظف لتتمكن من الوصول إلى صلاحياتك وخطتك." : "سجّل الدخول للوصول إلى حسابك وخطتك الميدانية."}</Text></View>{!isSupabaseConfigured ? <Text style={styles.error}>لا توجد إعدادات اتصال معتمدة بعد.</Text> : <><Text style={styles.label}>البريد الإلكتروني</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" style={styles.input} textAlign="right" placeholder="name@tips.sd" placeholderTextColor="#94A39C" />{isCreating ? <><Text style={styles.label}>الاسم الكامل</Text><TextInput value={fullName} onChangeText={setFullName} style={styles.input} textAlign="right" placeholder="الاسم كما يظهر للإدارة" placeholderTextColor="#94A39C" /></> : null}<Text style={styles.label}>كلمة المرور</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry style={styles.input} textAlign="right" placeholder="ثمانية أحرف على الأقل" placeholderTextColor="#94A39C" /><TouchableOpacity disabled={submitting} onPress={submit} style={[styles.button, submitting && { opacity: 0.6 }]}>{submitting ? <ActivityIndicator color="#FFFFFF" /> : <><MaterialIcons name={isCreating ? "person-add" : "login"} size={19} color="#FFFFFF" /><Text style={styles.buttonText}>{isCreating ? "إنشاء حساب" : "تسجيل الدخول"}</Text></>}</TouchableOpacity>{!isCreating ? <TouchableOpacity disabled={resetting} onPress={() => void requestPasswordReset()} style={styles.recovery}><Text style={styles.recoveryText}>{resetting ? "جارٍ إرسال الرابط…" : "نسيت كلمة المرور؟"}</Text></TouchableOpacity> : null}<TouchableOpacity onPress={() => setCreating((current) => !current)} style={styles.switch}><Text style={styles.switchText}>{isCreating ? "لديك حساب بالفعل؟ سجّل الدخول" : "ليس لديك حساب؟ أنشئ حساباً"}</Text></TouchableOpacity></>}</View></ScreenContainer>;
}
const styles = StyleSheet.create({ wrap: { flex: 1, justifyContent: "center", maxWidth: 420, width: "100%", alignSelf: "center" }, hero: { alignItems: "center", marginBottom: 34 }, mark: { width: 62, height: 62, borderRadius: 20, backgroundColor: palette.primary, alignItems: "center", justifyContent: "center", marginBottom: 13 }, markText: { color: "#FFFFFF", fontSize: 30, fontWeight: "900" }, title: { color: palette.ink, fontSize: 25, fontWeight: "900", textAlign: "center" }, copy: { color: palette.muted, fontSize: 13, lineHeight: 20, textAlign: "center", marginTop: 7 }, label: { color: palette.ink, fontSize: 12, fontWeight: "900", textAlign: "right", marginBottom: 7, marginTop: 14 }, input: { height: 50, backgroundColor: "#FFFFFF", borderColor: "#DCE8E3", borderWidth: 1, borderRadius: 14, paddingHorizontal: 13, color: palette.ink, fontSize: 14 }, button: { height: 52, backgroundColor: palette.primary, borderRadius: 15, marginTop: 22, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8 }, buttonText: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" }, recovery: { alignItems: "center", paddingTop: 13 }, recoveryText: { color: palette.primary, fontSize: 12, fontWeight: "900" }, claim: { marginTop: 16, padding: 11, borderRadius: 12, backgroundColor: "#FFF6E5" }, claimText: { color: palette.warning, fontSize: 11, fontWeight: "900", textAlign: "center" }, switch: { paddingVertical: 16, alignItems: "center" }, switchText: { color: palette.primary, fontSize: 12, fontWeight: "800" }, error: { color: palette.error, fontSize: 13, textAlign: "center" }, card: { width: "100%", maxWidth: 350, backgroundColor: "#FFFFFF", borderColor: "#E1EBE6", borderWidth: 1, borderRadius: 22, padding: 24, alignItems: "center" } });
