import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Image, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { AppHeader, palette } from "@/components/crm-ui";
import { ScreenContainer } from "@/components/screen-container";
import { listCatalogProducts, type CatalogProduct } from "@/lib/visit-product-context";

export default function ProductCatalogPage() {
  const [products, setProducts] = useState<CatalogProduct[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setProducts(await listCatalogProducts()); } catch { setProducts([]); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const visibleProducts = useMemo(() => { const normalized = query.trim().toLowerCase(); return normalized ? products.filter((product) => `${product.name} ${product.sku ?? ""} ${product.category ?? ""} ${product.description ?? ""}`.toLowerCase().includes(normalized)) : products; }, [products, query]);
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.page}><AppHeader eyebrow="منتجات الشركة المتاحة للزيارات" title="كتالوج المنتجات" right={<TouchableOpacity onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-forward" size={20} color={palette.primary} /></TouchableOpacity>} /><View style={styles.hero}><View style={styles.heroIcon}><MaterialIcons name="inventory-2" size={25} color="#FFFFFF" /></View><View style={{ flex: 1, alignItems: "flex-end" }}><Text style={styles.heroTitle}>اعرف المنتج قبل الزيارة</Text><Text style={styles.heroCopy}>راجع المنتج والسعر المعتمد عند توفره، ثم وثّق ما تم ترويجه أو مناقشته داخل تقرير الزيارة.</Text></View></View><View style={styles.search}><MaterialIcons name="search" size={20} color={palette.muted} /><TextInput value={query} onChangeText={setQuery} placeholder="ابحث بالاسم أو الرمز أو الفئة" placeholderTextColor="#93A099" textAlign="right" style={styles.searchInput} /></View>{loading ? <View style={styles.state}><ActivityIndicator color={palette.primary} /></View> : visibleProducts.length ? <View style={styles.list}>{visibleProducts.map((product) => <View key={product.id} style={styles.product}>{product.imageUrl ? <Image source={{ uri: product.imageUrl }} style={styles.productImage} /> : <View style={styles.productIcon}><MaterialIcons name="medication" size={21} color={palette.primary} /></View>}<View style={{ flex: 1, alignItems: "flex-end" }}><Text style={styles.name}>{product.name}</Text><Text style={styles.category}>{product.sku ? `${product.sku} · ` : ""}{product.category || "منتج الشركة"} · {product.unitLabel}</Text>{product.isOrderable && product.listPrice ? <Text style={styles.price}>{product.listPrice.toLocaleString("en-US")} {product.priceCurrency || "SDG"}</Text> : null}{product.description ? <Text style={styles.description}>{product.description}</Text> : null}</View></View>)}</View> : <View style={styles.empty}><MaterialIcons name="inventory-2" size={32} color={palette.primary} /><Text style={styles.emptyTitle}>{products.length ? "لا توجد نتائج مطابقة" : "لا يوجد كتالوج متاح بعد"}</Text><Text style={styles.emptyCopy}>{products.length ? "غيّر عبارة البحث أو امسحها." : "سيظهر هنا ما يضيفه مدير الشركة من منتجات صالحة للزيارة."}</Text></View>}<View style={styles.note}><MaterialIcons name="verified-user" size={18} color="#246B91" /><Text style={styles.noteText}>السعر، عند ظهوره، هو السعر المعتمد للفواتير المبدئية فقط؛ لا يؤكد مخزوناً أو فاتورة نهائية.</Text></View></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ page: { paddingTop: 10, paddingBottom: 34 }, back: { height: 40, width: 40, borderRadius: 13, backgroundColor: "#E9F8F2", alignItems: "center", justifyContent: "center" }, hero: { marginTop: 15, minHeight: 106, borderRadius: 20, backgroundColor: "#143D35", padding: 16, flexDirection: "row-reverse", alignItems: "center", gap: 12 }, heroIcon: { height: 48, width: 48, borderRadius: 16, backgroundColor: "#28715F", alignItems: "center", justifyContent: "center" }, heroTitle: { color: "#FFFFFF", fontSize: 16, fontWeight: "900", textAlign: "right" }, heroCopy: { color: "#C6E6DD", fontSize: 10, lineHeight: 16, textAlign: "right", marginTop: 5 }, search: { marginTop: 14, minHeight: 49, borderRadius: 14, paddingHorizontal: 13, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D7E9E2", flexDirection: "row-reverse", alignItems: "center", gap: 8 }, searchInput: { flex: 1, color: palette.ink, fontSize: 12 }, state: { minHeight: 140, alignItems: "center", justifyContent: "center" }, list: { marginTop: 12, gap: 8 }, product: { minHeight: 70, padding: 12, borderRadius: 16, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E0EBE6", flexDirection: "row-reverse", gap: 10, alignItems: "center" }, productIcon: { height: 39, width: 39, borderRadius: 13, backgroundColor: "#EAF8F2", alignItems: "center", justifyContent: "center" }, productImage: { height: 48, width: 48, borderRadius: 13, backgroundColor: "#EAF8F2" }, name: { color: palette.ink, fontSize: 13, fontWeight: "900", textAlign: "right" }, category: { color: palette.primary, fontSize: 10, fontWeight: "700", marginTop: 3, textAlign: "right" }, price: { color: "#246B91", fontSize: 10, fontWeight: "900", marginTop: 4, textAlign: "right" }, description: { color: palette.muted, fontSize: 10, lineHeight: 14, marginTop: 4, textAlign: "right" }, empty: { marginTop: 20, minHeight: 190, borderRadius: 18, padding: 22, backgroundColor: "#F7FBF9", alignItems: "center", justifyContent: "center", gap: 8 }, emptyTitle: { color: palette.ink, fontSize: 14, fontWeight: "900" }, emptyCopy: { color: palette.muted, fontSize: 11, lineHeight: 17, textAlign: "center", maxWidth: 260 }, note: { marginTop: 16, padding: 12, borderRadius: 14, backgroundColor: "#F1F8FC", flexDirection: "row-reverse", gap: 8, alignItems: "center" }, noteText: { color: "#246B91", fontSize: 10, lineHeight: 15, flex: 1, textAlign: "right" } });
