import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Alert, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { palette } from "@/components/crm-ui";
import { ScreenContainer } from "@/components/screen-container";
import { validateNewPassword } from "@/lib/password-policy";
import { supabase } from "@/lib/supabase-client";
import { useSupabaseAuth } from "@/lib/supabase-auth";

export default function ResetPasswordScreen() {
  const { session, loading } = useSupabaseAuth(); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [saving, setSaving] = useState(false);
  const save = async () => { const problem = validateNewPassword(password, confirmation); if (problem) { Alert.alert("راجع كلمة المرور", problem); return; } if (!supabase || !session) { Alert.alert("الرابط غير صالح", "افتح رابط الاستعادة الجديد من بريدك الإلكتروني ثم أعد المحاولة."); return; } setSaving(true); try { const { error } = await supabase.auth.updateUser({ password }); if (error) throw error; Alert.alert("تم تحديث كلمة المرور", "يمكنك تسجيل الدخول الآن بكلمة المرور الجديدة.", [{ text: "متابعة", onPress: () => router.replace("/login" as never) }]); } catch (error) { Alert.alert("تعذر التحديث", error instanceof Error ? error.message : "أرسل رابط استعادة جديداً ثم أعد المحاولة."); } finally { setSaving(false); } };
  if (loading) return <ScreenContainer className="items-center justify-center"><ActivityIndicator color={palette.primary} /></ScreenContainer>;
  return <ScreenContainer className="px-5" containerClassName="bg-background"><View style={styles.wrap}><View style={styles.mark}><MaterialIcons name="lock-reset" size={29} color="#FFFFFF" /></View><Text style={styles.title}>إعادة تعيين كلمة المرور</Text><Text style={styles.copy}>{session ? "اختر كلمة مرور جديدة قوية لحسابك." : "افتح رابط الاستعادة الذي وصلك إلى بريدك، ثم ارجع لهذه الشاشة."}</Text>{session ? <><Text style={styles.label}>كلمة المرور الجديدة</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="ثمانية أحرف على الأقل" placeholderTextColor="#94A39C" style={styles.input} textAlign="right" /><Text style={styles.label}>تأكيد كلمة المرور</Text><TextInput value={confirmation} onChangeText={setConfirmation} secureTextEntry placeholder="أعد كتابة كلمة المرور" placeholderTextColor="#94A39C" style={styles.input} textAlign="right" /><TouchableOpacity disabled={saving} onPress={() => void save()} style={[styles.button, saving && { opacity: 0.6 }]}>{saving ? <ActivityIndicator color="#FFFFFF" /> : <><MaterialIcons name="check" size={19} color="#FFFFFF" /><Text style={styles.buttonText}>حفظ كلمة المرور</Text></>}</TouchableOpacity></> : null}<TouchableOpacity onPress={() => router.replace("/login" as never)} style={styles.back}><Text style={styles.backText}>العودة إلى تسجيل الدخول</Text></TouchableOpacity></View></ScreenContainer>;
}

const styles = StyleSheet.create({ wrap: { flex: 1, justifyContent: "center", maxWidth: 420, width: "100%", alignSelf: "center" }, mark: { width: 62, height: 62, borderRadius: 20, backgroundColor: palette.primary, alignItems: "center", justifyContent: "center", alignSelf: "center", marginBottom: 14 }, title: { color: palette.ink, fontSize: 24, fontWeight: "900", textAlign: "center" }, copy: { color: palette.muted, fontSize: 13, lineHeight: 21, textAlign: "center", marginTop: 8, marginBottom: 17 }, label: { color: palette.ink, fontSize: 12, fontWeight: "900", textAlign: "right", marginBottom: 7, marginTop: 11 }, input: { height: 50, backgroundColor: "#FFFFFF", borderColor: "#DCE8E3", borderWidth: 1, borderRadius: 14, paddingHorizontal: 13, color: palette.ink, fontSize: 14 }, button: { height: 52, backgroundColor: palette.primary, borderRadius: 15, marginTop: 22, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8 }, buttonText: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" }, back: { alignItems: "center", paddingVertical: 18 }, backText: { color: palette.primary, fontSize: 12, fontWeight: "900" } });
