REVOKE ALL ON FUNCTION tips_crm.handle_auth_user_created() FROM PUBLIC;
REVOKE ALL ON FUNCTION tips_crm.log_audit(text, text, text, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_my_profile() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_mark_password_changed() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_claim_first_system_admin() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_list_roles() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_save_role(text, text, text, text[], boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_deactivate_role(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_list_invites() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_create_invite(text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_resend_invite(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_revoke_invite(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_accept_invite(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_list_accounts() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_sync_account(text, text, text, text, text, text, text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_list_visit_outcomes() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_save_visit_outcome(text, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_set_visit_outcome_active(uuid, boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_create_plan(text, text, date, date) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_save_visit(uuid, text, text, text, numeric, numeric, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_my_workspace() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_audit_feed() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_list_plans() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_update_plan_by_manager(uuid, jsonb, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_review_plan(uuid, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_prepare_plan_submission_email(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_prepare_invite_email(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_record_invite_email_delivery(uuid, text, text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_list_invite_email_deliveries() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_get_mail_settings() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_save_mail_settings(text, text, text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_export_report_feed(date, date, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_finalize_employee_account(uuid, text, text, text, text[], boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_check_company_user_limit(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.tips_crm_update_company_subscription(uuid, text, integer) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.tips_crm_my_profile() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.tips_crm_mark_password_changed() TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_claim_first_system_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_list_roles() TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_save_role(text, text, text, text[], boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_deactivate_role(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_list_invites() TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_create_invite(text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_resend_invite(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_revoke_invite(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_accept_invite(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_list_accounts() TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_sync_account(text, text, text, text, text, text, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_list_visit_outcomes() TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_save_visit_outcome(text, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_set_visit_outcome_active(uuid, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_create_plan(text, text, date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_save_visit(uuid, text, text, text, numeric, numeric, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_my_workspace() TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_audit_feed() TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_list_plans() TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_update_plan_by_manager(uuid, jsonb, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_review_plan(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_prepare_plan_submission_email(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_prepare_invite_email(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_record_invite_email_delivery(uuid, text, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_list_invite_email_deliveries() TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_get_mail_settings() TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_save_mail_settings(text, text, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_export_report_feed(date, date, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_finalize_employee_account(uuid, text, text, text, text[], boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tips_crm_check_company_user_limit(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.tips_crm_update_company_subscription(uuid, text, integer) TO authenticated, service_role;
