import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, usePathname } from "expo-router";
import { type ReactNode, useState } from "react";
import { ActivityIndicator, Alert, Platform, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { palette } from "@/components/crm-ui";
import { useSupabaseAuth } from "@/lib/supabase-auth";

const navigation = [{ label: "نظرة عامة", icon: "dashboard" as const, href: "/admin" }, { label: "مركز العمليات", icon: "monitor-heart" as const, href: "/admin/operations" }, { label: "التحصيل اليومي", icon: "receipt-long" as const, href: "/admin/daily-collections" }, { label: "الفريق", icon: "groups" as const, href: "/admin/team" }, { label: "نتائج الزيارة", icon: "playlist-add-check" as const, href: "/admin/outcomes" }, { label: "هوية البريد", icon: "markunread-mailbox" as const, href: "/admin/mail" }, { label: "الأدوار", icon: "admin-panel-settings" as const, href: "/admin/roles" }, { label: "سجل التدقيق", icon: "fact-check" as const, href: "/admin/audit" }];

export function AdminWebShell({ children, title }: { children: ReactNode; title: string }) {
  const pathname = usePathname();
  const { session, loading, profile, claimFirstSystemAdmin } = useSupabaseAuth();
  const [claimingFirstAdmin, setClaimingFirstAdmin] = useState(false);
  const claimFirstAdmin = async () => { setClaimingFirstAdmin(true); const success = await claimFirstSystemAdmin(); setClaimingFirstAdmin(false); if (success) Alert.alert("تمت التهيئة", "أصبح هذا الحساب مدير النظام الأول. يمكنك الآن متابعة بوابة الإدارة."); else Alert.alert("لا يمكن التهيئة", "يوجد مدير نظام بالفعل أو لم يتم التعرف على هذا الحساب. اطلب من مدير النظام تعيين دورك."); };
  if (Platform.OS !== "web") return <View style={styles.mobileNotice}><MaterialIcons name="laptop-mac" size={34} color={palette.primary} /><Text style={styles.mobileTitle}>بوابة الإدارة للويب</Text><Text style={styles.mobileCopy}>استخدم لوحة الإدارة من متصفح جهاز مكتبي أو لوحي للحصول على مساحة عمل كاملة.</Text></View>;
  if (loading) return <View style={styles.mobileNotice}><Text style={styles.mobileCopy}>يجري التحقق من الجلسة…</Text></View>;
  if (!session) return <View style={styles.mobileNotice}><MaterialIcons name="lock-outline" size={34} color={palette.primary} /><Text style={styles.mobileTitle}>تسجيل الدخول مطلوب</Text><Text style={styles.mobileCopy}>تحتاج إلى حساب معتمد للوصول إلى بوابة الإدارة.</Text><TouchableOpacity onPress={() => router.replace("/login" as never)} style={[styles.navItem, styles.navItemActive]}><Text style={styles.navTextActive}>تسجيل الدخول</Text></TouchableOpacity></View>;
  if (!profile?.permissions.includes("all") && !profile?.permissions.includes("view_team_data")) return <View style={styles.mobileNotice}><MaterialIcons name="admin-panel-settings" size={34} color={palette.primary} /><Text style={styles.mobileTitle}>بانتظار صلاحية الإدارة</Text><Text style={styles.mobileCopy}>{profile ? "يمكن لمدير النظام تعيين دور إداري لحسابك من بوابة الفريق." : "لا يوجد ملف وظيفي لهذا الحساب بعد. إذا كنت المسؤول الذي بدأ النظام، يمكنك تهيئة حسابك كمدير النظام الأول."}</Text>{!profile ? <TouchableOpacity disabled={claimingFirstAdmin} onPress={() => void claimFirstAdmin()} style={[styles.bootstrapButton, claimingFirstAdmin && { opacity: .6 }]}>{claimingFirstAdmin ? <ActivityIndicator color="#FFFFFF" /> : <Text style={styles.bootstrapText}>تهيئة حسابي كمدير النظام الأول</Text>}</TouchableOpacity> : null}</View>;
  const fullName = profile?.full_name ?? "موظف Tips";
  const initials = fullName.split(" ").slice(0, 2).map((part) => part[0]).join(" ");
  return <View style={styles.root}><View style={styles.sidebar}><View style={styles.brand}><View style={styles.brandMark}><Text style={styles.brandMarkText}>T</Text></View><View><Text style={styles.brandName}>Tips CRM</Text><Text style={styles.brandKicker}>بوابة الإدارة</Text></View></View><View style={styles.nav}>{navigation.map((item) => { const isActive = pathname === item.href; return <TouchableOpacity key={item.href} onPress={() => router.replace(item.href as never)} style={[styles.navItem, isActive && styles.navItemActive]}><MaterialIcons name={item.icon} size={20} color={isActive ? "#FFFFFF" : "#9CB8B0"} /><Text style={[styles.navText, isActive && styles.navTextActive]}>{item.label}</Text></TouchableOpacity>; })}</View><View style={styles.sidebarFoot}><View style={styles.onlineDot} /><Text style={styles.sidebarFootText}>النظام متصل</Text></View></View><View style={styles.main}><View style={styles.topbar}><View style={styles.topbarLeft}><View style={styles.avatar}><Text style={styles.avatarText}>{initials}</Text></View><View><Text style={styles.adminName}>{fullName}</Text><Text style={styles.adminRole}>{profile?.role_name ?? "بانتظار التعيين"}</Text></View></View><Text style={styles.pageTitle}>{title}</Text></View><View style={styles.content}>{children}</View></View></View>;
}

const styles = StyleSheet.create({ root: { flex: 1, minHeight: "100%" as unknown as number, flexDirection: "row-reverse", backgroundColor: "#F5F8F7" }, sidebar: { width: 236, backgroundColor: "#102D27", padding: 22, justifyContent: "space-between" }, brand: { flexDirection: "row-reverse", gap: 10, alignItems: "center" }, brandMark: { width: 40, height: 40, borderRadius: 13, backgroundColor: "#14A687", alignItems: "center", justifyContent: "center" }, brandMarkText: { color: "#FFFFFF", fontSize: 19, fontWeight: "900" }, brandName: { color: "#FFFFFF", fontSize: 17, fontWeight: "900", textAlign: "right" }, brandKicker: { color: "#8DB2A7", fontSize: 10, marginTop: 2, textAlign: "right" }, nav: { gap: 8, marginTop: 42, flex: 1 }, navItem: { minHeight: 46, paddingHorizontal: 13, borderRadius: 12, flexDirection: "row-reverse", alignItems: "center", gap: 10 }, navItemActive: { backgroundColor: "#0A755F" }, navText: { color: "#B8CDC7", fontSize: 13, fontWeight: "800" }, navTextActive: { color: "#FFFFFF" }, sidebarFoot: { flexDirection: "row-reverse", gap: 7, alignItems: "center", paddingTop: 12, borderTopWidth: 1, borderTopColor: "#24433B" }, onlineDot: { height: 8, width: 8, borderRadius: 4, backgroundColor: "#4BE2A8" }, sidebarFootText: { color: "#9CB8B0", fontSize: 11 }, main: { flex: 1 }, topbar: { minHeight: 78, paddingHorizontal: 34, backgroundColor: "#FFFFFF", borderBottomWidth: 1, borderBottomColor: "#E6EEEA", flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, pageTitle: { color: palette.ink, fontSize: 21, fontWeight: "900" }, topbarLeft: { flexDirection: "row-reverse", gap: 9, alignItems: "center" }, avatar: { width: 34, height: 34, borderRadius: 12, backgroundColor: "#E6F6F0", alignItems: "center", justifyContent: "center" }, avatarText: { color: palette.primary, fontSize: 10, fontWeight: "900" }, adminName: { color: palette.ink, fontSize: 12, fontWeight: "800", textAlign: "right" }, adminRole: { color: palette.muted, fontSize: 10, marginTop: 1, textAlign: "right" }, content: { flex: 1, padding: 26, maxWidth: 1360, width: "100%", alignSelf: "center" }, mobileNotice: { flex: 1, backgroundColor: "#F6F8F7", justifyContent: "center", alignItems: "center", padding: 30, gap: 12 }, mobileTitle: { color: palette.ink, fontSize: 21, fontWeight: "900" }, mobileCopy: { color: palette.muted, fontSize: 13, textAlign: "center", lineHeight: 20, maxWidth: 280 }, bootstrapButton: { minHeight: 47, marginTop: 7, paddingHorizontal: 16, borderRadius: 13, backgroundColor: palette.primary, alignItems: "center", justifyContent: "center" }, bootstrapText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" } });
