import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useEffect, useState } from "react";
import { Alert, Platform, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { palette } from "@/components/crm-ui";
import { getDutyTrackingState, startDirectDutyTracking, stopDirectDutyTracking, subscribeToDutyPoints, type DutyTrackingState } from "@/lib/duty-tracker";
import type { DutyPoint } from "@/lib/duty-tracker";

export function DutyTrackerCard({ onPoint }: { onPoint: (point: DutyPoint) => void }) {
  const [state, setState] = useState<DutyTrackingState>({ enabled: false, backgroundEnabled: false }); const [busy, setBusy] = useState(false);
  useEffect(() => { void getDutyTrackingState().then(setState); const unsubscribe = subscribeToDutyPoints((point) => { setState((current) => ({ ...current, enabled: true, lastPoint: point })); onPoint(point); }); return unsubscribe; }, [onPoint]);
  const start = () => Alert.alert("بدء تتبع الدوام", "سيشارك التطبيق موقعك ومسار تنقلك مع الإدارة أثناء جلسة الدوام فقط. يمكنك الإيقاف في أي وقت.", [{ text: "إلغاء", style: "cancel" }, { text: "موافق وبدء الدوام", onPress: async () => { setBusy(true); try { const next = await startDirectDutyTracking(); setState((current) => ({ ...current, enabled: true, startedAt: new Date().toISOString(), backgroundEnabled: next.backgroundEnabled })); if (!next.backgroundEnabled && Platform.OS !== "web") Alert.alert("التتبع يعمل أثناء فتح التطبيق", "للتتبع بالخلفية فعّل إذن الموقع الدائم من إعدادات الهاتف واستخدم نسخة التطبيق المخصصة."); } catch (error) { Alert.alert("تعذر بدء التتبع", error instanceof Error ? error.message : "تحقق من إعدادات الموقع ثم حاول مرة أخرى."); } finally { setBusy(false); } } }]);
  const stop = async () => { setBusy(true); try { await stopDirectDutyTracking(); setState((current) => ({ ...current, enabled: false, backgroundEnabled: false })); } finally { setBusy(false); } };
  return <View style={[styles.card, state.enabled && styles.cardActive]}><View style={styles.icon}><MaterialIcons name={state.enabled ? "gps-fixed" : "gps-off"} size={21} color={state.enabled ? palette.success : palette.muted} /></View><View style={{ flex: 1, alignItems: "flex-end" }}><Text style={styles.title}>{state.enabled ? "الدوام المباشر يعمل" : "تتبع الدوام المباشر"}</Text><Text style={styles.subtitle}>{state.enabled ? (state.backgroundEnabled ? "يتم تحديث الموقع في الخلفية أثناء الدوام" : "يتم التحديث عند فتح التطبيق") : "ابدأ الجلسة لمشاركة موقعك ومسار اليوم مع الإدارة"}</Text>{state.lastPoint ? <Text style={styles.lastPoint}>آخر تحديث: {new Date(state.lastPoint.capturedAt).toLocaleTimeString("ar", { hour: "2-digit", minute: "2-digit" })}</Text> : null}</View><TouchableOpacity disabled={busy} onPress={state.enabled ? stop : start} style={[styles.button, state.enabled && styles.stopButton]}><Text style={[styles.buttonText, state.enabled && styles.stopText]}>{busy ? "…" : state.enabled ? "إيقاف" : "بدء"}</Text></TouchableOpacity></View>;
}
const styles = StyleSheet.create({ card: { marginTop: 14, borderRadius: 18, backgroundColor: "#FFFFFF", borderColor: palette.line, borderWidth: 1, padding: 13, flexDirection: "row", alignItems: "center", gap: 10 }, cardActive: { backgroundColor: "#F4FCF9", borderColor: "#9ED5C6" }, icon: { height: 39, width: 39, borderRadius: 13, backgroundColor: "#EAF7F2", alignItems: "center", justifyContent: "center" }, title: { color: palette.ink, fontSize: 14, fontWeight: "800", textAlign: "right" }, subtitle: { color: palette.muted, fontSize: 10, lineHeight: 15, marginTop: 3, textAlign: "right" }, lastPoint: { color: palette.success, fontSize: 10, fontWeight: "700", marginTop: 4, textAlign: "right" }, button: { minWidth: 51, borderRadius: 11, backgroundColor: palette.primary, paddingHorizontal: 10, paddingVertical: 10, alignItems: "center" }, stopButton: { backgroundColor: "#FFF0F0" }, buttonText: { color: "#FFFFFF", fontSize: 11, fontWeight: "800" }, stopText: { color: palette.error } });
