import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import Svg, { Circle, Path, Rect } from "react-native-svg";
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { palette } from "@/components/crm-ui";

export type LiveRepPosition = { id: string; name: string; initials: string; role: string; territory: string; latitude: number; longitude: number; updatedAt: string; active: boolean; path: Array<{ latitude: number; longitude: number }> };

function project(point: { latitude: number; longitude: number }, items: LiveRepPosition[]) {
  const all = items.flatMap((item) => item.path.length ? item.path : [{ latitude: item.latitude, longitude: item.longitude }]);
  const lats = all.map((item) => item.latitude); const lngs = all.map((item) => item.longitude);
  const minLat = Math.min(...lats) - 0.005; const maxLat = Math.max(...lats) + 0.005; const minLng = Math.min(...lngs) - 0.005; const maxLng = Math.max(...lngs) + 0.005;
  return { x: 24 + ((point.longitude - minLng) / Math.max(maxLng - minLng, 0.001)) * 312, y: 192 - ((point.latitude - minLat) / Math.max(maxLat - minLat, 0.001)) * 162 };
}

export function LiveDutyMap({ reps, selectedId, onSelect }: { reps: LiveRepPosition[]; selectedId: string; onSelect: (id: string) => void }) {
  const selected = reps.find((item) => item.id === selectedId) ?? reps[0];
  const path = selected?.path.length ? selected.path : selected ? [{ latitude: selected.latitude, longitude: selected.longitude }] : [];
  const pathD = path.map((point, index) => { const pos = project(point, reps); return `${index ? "L" : "M"}${pos.x} ${pos.y}`; }).join(" ");
  return <View style={styles.wrap}><View style={styles.canvas}><Svg width="100%" height="215" viewBox="0 0 360 215" preserveAspectRatio="none"><Rect width="360" height="215" fill="#EAF6F2" /><Path d="M0 45 C75 15 128 78 186 45 S286 17 360 66" stroke="#B8DED3" strokeWidth="17" fill="none" opacity="0.82" /><Path d="M0 167 C63 138 116 194 180 159 S286 132 360 177" stroke="#C5E5DD" strokeWidth="13" fill="none" opacity="0.75" /><Path d="M0 99 H360 M0 143 H360" stroke="#D5E9E3" strokeWidth="1.2" strokeDasharray="4 5" />{pathD ? <Path d={pathD} stroke="#E4A111" strokeWidth="3" fill="none" strokeDasharray="7 5" /> : null}{reps.map((rep) => { const pos = project(rep, reps); const isSelected = rep.id === selected?.id; return <Circle key={rep.id} cx={pos.x} cy={pos.y} r={isSelected ? 10 : 7} fill={rep.active ? "#0D9488" : "#94A3A0"} stroke="#FFFFFF" strokeWidth="4" />; })}</Svg><View style={styles.mapBadge}><MaterialIcons name="gps-fixed" size={15} color={palette.success} /><Text style={styles.mapBadgeText}>تحديث مباشر</Text></View></View><View style={styles.repList}>{reps.map((rep) => <TouchableOpacity key={rep.id} onPress={() => onSelect(rep.id)} style={[styles.rep, selected?.id === rep.id && styles.repActive]}><View style={[styles.avatar, { backgroundColor: rep.active ? "#0D9488" : "#94A3A0" }]}><Text style={styles.avatarText}>{rep.initials}</Text></View><View style={{ flex: 1, alignItems: "flex-end" }}><Text style={styles.repName}>{rep.name}</Text><Text style={styles.repMeta}>{rep.territory} · {rep.updatedAt}</Text></View><View style={[styles.status, { backgroundColor: rep.active ? "#E9F8F2" : "#F1F4F2" }]}><Text style={[styles.statusText, { color: rep.active ? palette.success : palette.muted }]}>{rep.active ? "على الدوام" : "متوقف"}</Text></View></TouchableOpacity>)}</View>{selected ? <View style={styles.routeSummary}><MaterialIcons name="route" size={18} color={palette.primary} /><Text style={styles.routeText}>مسار {selected.name} اليوم · {Math.max(selected.path.length - 1, 0)} نقاط انتقال مسجلة</Text></View> : null}</View>;
}
const styles = StyleSheet.create({ wrap: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: palette.line, borderRadius: 19, overflow: "hidden" }, canvas: { height: 215, position: "relative", overflow: "hidden" }, mapBadge: { position: "absolute", right: 12, top: 12, flexDirection: "row", gap: 5, alignItems: "center", backgroundColor: "#FFFFFF", borderRadius: 10, paddingHorizontal: 9, paddingVertical: 6 }, mapBadgeText: { color: palette.success, fontSize: 10, fontWeight: "800" }, repList: { paddingHorizontal: 11, paddingTop: 7 }, rep: { paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: "#EDF1EF", flexDirection: "row", alignItems: "center", gap: 9 }, repActive: { backgroundColor: "#FAFFFD" }, avatar: { height: 34, width: 34, borderRadius: 11, alignItems: "center", justifyContent: "center" }, avatarText: { color: "#FFFFFF", fontWeight: "800", fontSize: 10 }, repName: { color: palette.ink, fontSize: 12, fontWeight: "800", textAlign: "right" }, repMeta: { color: palette.muted, fontSize: 10, marginTop: 2, textAlign: "right" }, status: { paddingVertical: 4, paddingHorizontal: 7, borderRadius: 8 }, statusText: { fontSize: 9, fontWeight: "800" }, routeSummary: { flexDirection: "row", gap: 7, alignItems: "center", backgroundColor: "#E9F8F2", padding: 11 }, routeText: { flex: 1, color: palette.success, fontSize: 11, fontWeight: "700", textAlign: "right" } });
