import AsyncStorage from "@react-native-async-storage/async-storage";
import type { ProformaLineInput } from "@/lib/proforma-utils";

export type OfflineProformaPayload = { accountId: string; accountName: string; sourceVisitRef?: string; clientDraftRef: string; notes: string; lines: ProformaLineInput[] };
export type OfflineProformaDraft = { id: string; profileId: string; remoteProformaId?: string; payload: OfflineProformaPayload; status: "pending" | "failed"; createdAt: string; updatedAt: string; attempts: number; lastError?: string };
const keyFor = (profileId: string) => `tips-crm-offline-proforma-drafts-v1:${profileId}`;
const validDraft = (value: unknown): value is OfflineProformaDraft => Boolean(value && typeof value === "object" && typeof (value as OfflineProformaDraft).id === "string" && typeof (value as OfflineProformaDraft).profileId === "string" && typeof (value as OfflineProformaDraft).payload === "object");
export function createOfflineProformaDraft(input: { id: string; profileId: string; remoteProformaId?: string; payload: OfflineProformaPayload; now?: string }) { const now = input.now ?? new Date().toISOString(); return { id: input.id, profileId: input.profileId, remoteProformaId: input.remoteProformaId, payload: input.payload, status: "pending" as const, createdAt: now, updatedAt: now, attempts: 0 }; }
export async function listOfflineProformaDrafts(profileId: string) { const raw = await AsyncStorage.getItem(keyFor(profileId)); if (!raw) return []; try { return (JSON.parse(raw) as unknown[]).filter(validDraft).filter((draft) => draft.profileId === profileId).sort((a, b) => a.updatedAt.localeCompare(b.updatedAt)); } catch { return []; } }
export async function saveOfflineProformaDraft(draft: OfflineProformaDraft) { const current = await listOfflineProformaDrafts(draft.profileId); const next = [draft, ...current.filter((item) => item.id !== draft.id)]; await AsyncStorage.setItem(keyFor(draft.profileId), JSON.stringify(next)); return next; }
export async function removeOfflineProformaDraft(profileId: string, draftId: string) { const next = (await listOfflineProformaDrafts(profileId)).filter((item) => item.id !== draftId); await AsyncStorage.setItem(keyFor(profileId), JSON.stringify(next)); return next; }
export async function markOfflineProformaDraftFailed(profileId: string, draftId: string, error: string) { const next = (await listOfflineProformaDrafts(profileId)).map((item) => item.id === draftId ? { ...item, status: "failed" as const, attempts: item.attempts + 1, lastError: error.slice(0, 240), updatedAt: new Date().toISOString() } : item); await AsyncStorage.setItem(keyFor(profileId), JSON.stringify(next)); return next; }
