import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { GeographicMap } from "@/components/geographic-map";
import { palette } from "@/components/crm-ui";
import type { TerritoryBoundary } from "@/lib/crm-store";

export type LiveRepPosition = { id: string; name: string; initials: string; role: string; territory: string; latitude: number; longitude: number; updatedAt: string; active: boolean; outsideTerritory?: boolean; path: Array<{ latitude: number; longitude: number }> };

export function LiveDutyMap({ reps, boundaries, selectedId, onSelect }: { reps: LiveRepPosition[]; boundaries: TerritoryBoundary[]; selectedId: string; onSelect: (id: string) => void }) {
  const selected = reps.find((item) => item.id === selectedId) ?? reps[0];
  return <View style={styles.wrap}>
    <View style={styles.canvas}><GeographicMap height={280} boundaries={boundaries} reps={reps} /><View style={styles.mapBadge}><MaterialIcons name="public" size={15} color={palette.success} /><Text style={styles.mapBadgeText}>خريطة جغرافية مباشرة</Text></View></View>
    <View style={styles.repList}>{reps.map((rep) => <TouchableOpacity key={rep.id} onPress={() => onSelect(rep.id)} style={[styles.rep, selected?.id === rep.id && styles.repActive]}><View style={[styles.avatar, { backgroundColor: rep.outsideTerritory ? "#DC2626" : rep.active ? "#0D9488" : "#94A3A0" }]}><Text style={styles.avatarText}>{rep.initials}</Text></View><View style={{ flex: 1, alignItems: "flex-end" }}><Text style={styles.repName}>{rep.name}</Text><Text style={[styles.repMeta, rep.outsideTerritory && styles.outsideMeta]}>{rep.territory} · {rep.updatedAt}</Text></View><View style={[styles.status, { backgroundColor: rep.outsideTerritory ? "#FFF1EF" : rep.active ? "#E9F8F2" : "#F1F4F2" }]}><Text style={[styles.statusText, { color: rep.outsideTerritory ? palette.error : rep.active ? palette.success : palette.muted }]}>{rep.outsideTerritory ? "خارج المناطق" : rep.active ? "على الدوام" : "متوقف"}</Text></View></TouchableOpacity>)}</View>
    {selected ? <View style={styles.routeSummary}><MaterialIcons name="route" size={18} color={palette.primary} /><Text style={styles.routeText}>مسار {selected.name} اليوم · {Math.max(selected.path.length - 1, 0)} نقاط انتقال مسجلة</Text></View> : null}
  </View>;
}

const styles = StyleSheet.create({ wrap: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: palette.line, borderRadius: 19, overflow: "hidden" }, canvas: { height: 280, position: "relative", overflow: "hidden" }, mapBadge: { position: "absolute", right: 12, top: 12, flexDirection: "row", gap: 5, alignItems: "center", backgroundColor: "#FFFFFF", borderRadius: 10, paddingHorizontal: 9, paddingVertical: 6, shadowColor: "#173C34", shadowOpacity: 0.12, shadowRadius: 6 }, mapBadgeText: { color: palette.success, fontSize: 10, fontWeight: "800" }, repList: { paddingHorizontal: 11, paddingTop: 7 }, rep: { paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: "#EDF1EF", flexDirection: "row", alignItems: "center", gap: 9 }, repActive: { backgroundColor: "#FAFFFD" }, avatar: { height: 34, width: 34, borderRadius: 11, alignItems: "center", justifyContent: "center" }, avatarText: { color: "#FFFFFF", fontWeight: "800", fontSize: 10 }, repName: { color: palette.ink, fontSize: 12, fontWeight: "800", textAlign: "right" }, repMeta: { color: palette.muted, fontSize: 10, marginTop: 2, textAlign: "right" }, outsideMeta: { color: palette.error, fontWeight: "800" }, status: { paddingVertical: 4, paddingHorizontal: 7, borderRadius: 8 }, statusText: { fontSize: 9, fontWeight: "800" }, routeSummary: { flexDirection: "row", gap: 7, alignItems: "center", backgroundColor: "#E9F8F2", padding: 11 }, routeText: { flex: 1, color: palette.success, fontSize: 11, fontWeight: "700", textAlign: "right" } });
