import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { AccountAvatar, AppHeader, PrimaryButton, palette } from "@/components/crm-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useCrm, type Plan } from "@/lib/crm-store";

export default function NewPlanScreen() {
  const { data, accountById, submitPlan } = useCrm();
  const [kind, setKind] = useState<Plan["kind"]>("أسبوعية");
  const [title, setTitle] = useState("خطة أسبوع جديد");
  const [period, setPeriod] = useState("18–22 أغسطس");
  const [selected, setSelected] = useState<string[]>(data.visits.filter((visit) => visit.status === "مجدولة").slice(0, 3).map((visit) => visit.id));
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((visitId) => visitId !== id) : [...current, id]);
  const submit = () => { if (!title.trim() || !period.trim() || selected.length === 0) { Alert.alert("الخطة غير مكتملة", "أدخل اسم الفترة وحدد زيارة واحدة على الأقل."); return; } submitPlan({ title: title.trim(), period: period.trim(), kind, visitIds: selected }); Alert.alert("تم إرسال الخطة", "أصبحت الخطة بانتظار اعتماد الإدارة.", [{ text: "حسناً", onPress: () => router.replace("/(tabs)/plans" as never) }]); };
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><AppHeader eyebrow="تنتقل الخطة إلى المدير للمراجعة" title="خطة جديدة" right={<TouchableOpacity onPress={() => router.back()} style={styles.back}><MaterialIcons name="close" size={21} color={palette.primary} /></TouchableOpacity>} />
    <Text style={styles.label}>نوع الخطة</Text><View style={styles.kindRow}>{(["أسبوعية", "شهرية"] as Plan["kind"][]).map((item) => <TouchableOpacity key={item} style={[styles.kind, kind === item && styles.kindActive]} onPress={() => setKind(item)}><Text style={[styles.kindText, kind === item && styles.kindTextActive]}>{item}</Text></TouchableOpacity>)}</View>
    <Field label="اسم الخطة" value={title} onChangeText={setTitle} /><Field label="الفترة" value={period} onChangeText={setPeriod} />
    <Text style={[styles.label, { marginTop: 4 }]}>زيارات الخطة · {selected.length} محددة</Text><View style={styles.visits}>{data.visits.filter((visit) => visit.status === "مجدولة").map((visit) => { const account = accountById(visit.accountId); if (!account) return null; const picked = selected.includes(visit.id); return <TouchableOpacity key={visit.id} style={[styles.visit, picked && styles.visitPicked]} onPress={() => toggle(visit.id)}><View style={[styles.check, picked && styles.checkPicked]}>{picked ? <MaterialIcons name="check" size={16} color="#FFFFFF" /> : null}</View><View style={{ flex: 1, alignItems: "flex-end" }}><Text style={styles.visitName}>{account.name}</Text><Text style={styles.visitMeta}>{visit.date} · {visit.time} · {account.area}</Text></View><AccountAvatar account={account} size={39} /></TouchableOpacity>; })}</View>
    <PrimaryButton label="إرسال للاعتماد" icon="send" onPress={submit} style={{ marginTop: 19 }} />
  </ScrollView></ScreenContainer>;
}
function Field({ label, value, onChangeText }: { label: string; value: string; onChangeText: (value: string) => void }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={styles.input} value={value} onChangeText={onChangeText} textAlign="right" placeholderTextColor="#93A099" returnKeyType="done" /></View>; }
const styles = StyleSheet.create({ content: { paddingTop: 10, paddingBottom: 28 }, back: { width: 40, height: 40, borderRadius: 14, backgroundColor: "#E9F8F2", alignItems: "center", justifyContent: "center" }, label: { color: palette.ink, fontSize: 13, fontWeight: "800", textAlign: "right", marginBottom: 8 }, kindRow: { flexDirection: "row-reverse", gap: 8, marginBottom: 17 }, kind: { flex: 1, padding: 12, alignItems: "center", borderRadius: 13, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: palette.line }, kindActive: { backgroundColor: "#E9F8F2", borderColor: "#A9D8CC" }, kindText: { color: palette.muted, fontWeight: "700", fontSize: 13 }, kindTextActive: { color: palette.primary }, field: { marginBottom: 15 }, input: { minHeight: 49, paddingHorizontal: 13, borderWidth: 1, borderColor: palette.line, borderRadius: 14, backgroundColor: "#FFFFFF", color: palette.ink, fontSize: 14 }, visits: { gap: 9 }, visit: { padding: 12, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: palette.line, borderRadius: 16, flexDirection: "row", alignItems: "center", gap: 10 }, visitPicked: { backgroundColor: "#F2FAF7", borderColor: "#97D1C2" }, check: { width: 23, height: 23, borderRadius: 8, borderWidth: 1.5, borderColor: "#C4CFCA", alignItems: "center", justifyContent: "center" }, checkPicked: { backgroundColor: palette.primary, borderColor: palette.primary }, visitName: { color: palette.ink, fontWeight: "800", fontSize: 14, textAlign: "right" }, visitMeta: { color: palette.muted, fontSize: 10, marginTop: 3, textAlign: "right" } });
