import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { AppHeader, PrimaryButton, palette } from "@/components/crm-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useCrm, type CrmNotification } from "@/lib/crm-store";
import { useAuth } from "@/hooks/use-auth";
import { trpc } from "@/lib/trpc";

const choices: Array<{ label: string; value: CrmNotification["kind"]; icon: keyof typeof MaterialIcons.glyphMap }> = [{ label: "تنبيه", value: "تنبيه", icon: "warning-amber" }, { label: "زيارة", value: "زيارة", icon: "location-on" }, { label: "خطة", value: "خطة", icon: "event-note" }, { label: "فريق", value: "فريق", icon: "groups" }];
const apiKind: Record<CrmNotification["kind"], "plan" | "visit" | "alert" | "team"> = { خطة: "plan", زيارة: "visit", تنبيه: "alert", فريق: "team" };
export default function NewAlertScreen() {
  const { createCentralNotification } = useCrm(); const { isAuthenticated } = useAuth(); const mutation = trpc.operations.createNotification.useMutation(); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [kind, setKind] = useState<CrmNotification["kind"]>("تنبيه");
  const send = () => { if (!title.trim() || !body.trim()) { Alert.alert("تنبيه ناقص", "أدخل عنوان التنبيه والنص الذي سيصل للفريق."); return; } const input = { title: title.trim(), body: body.trim(), kind }; createCentralNotification(input); if (isAuthenticated) mutation.mutate({ ...input, kind: apiKind[kind] }); Alert.alert("تم إرسال التنبيه", "ظهر التنبيه في مركز الفريق وسيُرسل كتذكير محلي عند توفر الإذن.", [{ text: "حسناً", onPress: () => router.replace("/notifications" as never) }]); };
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><AppHeader eyebrow="رسالة تشغيلية سريعة للفريق" title="إنشاء تنبيه" right={<TouchableOpacity onPress={() => router.back()} style={styles.back}><MaterialIcons name="close" size={20} color={palette.primary} /></TouchableOpacity>} /><Text style={styles.label}>نوع التنبيه</Text><View style={styles.choices}>{choices.map((item) => <TouchableOpacity key={item.value} onPress={() => setKind(item.value)} style={[styles.choice, kind === item.value && styles.choiceActive]}><MaterialIcons name={item.icon} size={18} color={kind === item.value ? palette.primary : palette.muted} /><Text style={[styles.choiceText, kind === item.value && styles.choiceTextActive]}>{item.label}</Text></TouchableOpacity>)}</View><Text style={[styles.label, { marginTop: 20 }]}>العنوان</Text><TextInput value={title} onChangeText={setTitle} placeholder="مثال: تأكيد خطة الغد" placeholderTextColor="#93A099" textAlign="right" style={styles.input} /><Text style={[styles.label, { marginTop: 16 }]}>نص التنبيه</Text><TextInput value={body} onChangeText={setBody} placeholder="اكتب التعليمات القصيرة المطلوبة من الفريق…" placeholderTextColor="#93A099" textAlign="right" multiline style={styles.body} /><View style={styles.preview}><MaterialIcons name="notifications-active" size={20} color={palette.primary} /><Text style={styles.previewText}>سيظهر التنبيه داخل مركز تنبيهات Tips CRM، ويُرسل للجهاز عند توفر الإذن.</Text></View><PrimaryButton label="إرسال التنبيه" icon="send" onPress={send} style={{ marginTop: 18 }} /></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 10, paddingBottom: 30 }, back: { width: 40, height: 40, borderRadius: 14, backgroundColor: "#E9F8F2", alignItems: "center", justifyContent: "center" }, label: { color: palette.ink, fontSize: 13, fontWeight: "800", textAlign: "right", marginBottom: 8 }, choices: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 8 }, choice: { width: "47%", flexGrow: 1, minHeight: 45, borderRadius: 12, borderColor: palette.line, borderWidth: 1, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 }, choiceActive: { borderColor: "#9DD3C4", backgroundColor: "#E9F8F2" }, choiceText: { color: palette.muted, fontWeight: "700", fontSize: 12 }, choiceTextActive: { color: palette.primary }, input: { minHeight: 48, borderWidth: 1, borderColor: palette.line, borderRadius: 13, backgroundColor: "#FFFFFF", paddingHorizontal: 12, color: palette.ink, fontSize: 14 }, body: { minHeight: 120, borderWidth: 1, borderColor: palette.line, borderRadius: 13, backgroundColor: "#FFFFFF", padding: 12, color: palette.ink, fontSize: 13, textAlignVertical: "top" }, preview: { marginTop: 14, borderRadius: 15, padding: 12, backgroundColor: "#E9F8F2", flexDirection: "row", gap: 8, alignItems: "flex-start" }, previewText: { color: palette.success, fontSize: 11, lineHeight: 17, flex: 1, textAlign: "right" } });
