// @ts-nocheck
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { AdminWebShell } from "@/components/admin-web-shell";
import { palette } from "@/components/crm-ui";
import { supabase } from "@/lib/supabase-client";
import { useSupabaseAuth } from "@/lib/supabase-auth";

const statuses = [{ key: "invited", label: "مدعو", color: "#6B7280" }, { key: "confirmed", label: "أكد الحضور", color: "#2563EB" }, { key: "declined", label: "اعتذر", color: "#B45309" }, { key: "attended", label: "حضر", color: "#0F766E" }, { key: "no_show", label: "لم يحضر", color: "#C2410C" }, { key: "follow_up", label: "يحتاج متابعة", color: "#7C3AED" }];

export default function MedicalEventDetailPage() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { profile } = useSupabaseAuth(); const [event, setEvent] = useState(null); const [invitations, setInvitations] = useState([]); const [loading, setLoading] = useState(true); const [note, setNote] = useState({});
  const canManage = Boolean(profile?.permissions.includes("all") || profile?.permissions.includes("view_team_data") || profile?.permissions.includes("export_reports"));
  const load = async () => { if (!supabase || !id || !canManage) return; setLoading(true); try { const [eventResult, invitationResult] = await Promise.all([supabase.schema("tips_crm").from("medical_events").select("*").eq("id", id).maybeSingle(), supabase.schema("tips_crm").from("medical_event_invitations").select("id, invitation_status, notes, responded_at, accounts(name, specialty, state, city)").eq("event_id", id).order("created_at")]); if (eventResult.error) throw eventResult.error; if (invitationResult.error) throw invitationResult.error; setEvent(eventResult.data); setInvitations(invitationResult.data ?? []); } catch (error) { Alert.alert("تعذر تحميل الفعالية", error instanceof Error ? error.message : "حاول مرة أخرى."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [id, canManage]);
  const updateInvitation = async (invitationId, status) => { if (!supabase) return; const { error } = await supabase.rpc("tips_crm_update_medical_event_invitation", { invitation_uuid: invitationId, next_status: status, note: note[invitationId] || null }); if (error) return Alert.alert("تعذر تحديث الدعوة", error.message); void load(); };
  if (!canManage) return <AdminWebShell title="دعوات الفعالية"><View style={styles.lock}><MaterialIcons name="lock-outline" size={34} color={palette.primary} /><Text style={styles.lockText}>صلاحية الإدارة مطلوبة</Text></View></AdminWebShell>;
  return <AdminWebShell title="دعوات الفعالية"><ScrollView contentContainerStyle={styles.page}><TouchableOpacity onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-forward" size={18} color={palette.primary} /><Text style={styles.backText}>العودة للبرنامج الطبي</Text></TouchableOpacity>{event ? <View style={styles.hero}><MaterialIcons name="event" size={27} color="#FFFFFF" /><View style={{ flex: 1, alignItems: "flex-end" }}><Text style={styles.heroTitle}>{event.title}</Text><Text style={styles.heroCopy}>{event.topic}{event.focus_product ? ` · ${event.focus_product}` : ""}</Text><Text style={styles.heroCopy}>{new Date(event.starts_at).toLocaleString("ar")} · {event.venue} · {event.city}</Text></View></View> : null}<Text style={styles.title}>دعوات الأطباء وحالة الحضور</Text><Text style={styles.copy}>حدّث الحالة بعد الاتصال أو بعد الفعالية. تسجّل كل عملية في سجل التدقيق.</Text>{loading ? <ActivityIndicator color={palette.primary} style={{ marginTop: 28 }} /> : <View style={styles.list}>{invitations.length ? invitations.map((invitation) => { const current = statuses.find((item) => item.key === invitation.invitation_status) ?? statuses[0]; const account = invitation.accounts; return <View key={invitation.id} style={styles.card}><View style={styles.cardHead}><View style={[styles.statusDot, { backgroundColor: current.color }]} /><View style={{ flex: 1, alignItems: "flex-end" }}><Text style={styles.doctor}>{account?.name ?? "طبيب"}</Text><Text style={styles.meta}>{account?.specialty ?? "تخصص غير محدد"} · {account?.city ?? ""}</Text><Text style={[styles.current, { color: current.color }]}>الحالة الحالية: {current.label}</Text></View></View><View style={styles.statuses}>{statuses.map((status) => <TouchableOpacity key={status.key} onPress={() => void updateInvitation(invitation.id, status.key)} style={[styles.status, invitation.invitation_status === status.key && { borderColor: status.color, backgroundColor: `${status.color}10` }]}><Text style={[styles.statusText, invitation.invitation_status === status.key && { color: status.color }]}>{status.label}</Text></TouchableOpacity>)}</View><TextInput value={note[invitation.id] ?? invitation.notes ?? ""} onChangeText={(value) => setNote((currentNotes) => ({ ...currentNotes, [invitation.id]: value }))} textAlign="right" placeholder="ملاحظة اختيارية: سبب الاعتذار أو خطوة المتابعة" placeholderTextColor="#93A099" style={styles.note} /></View>; }) : <View style={styles.empty}><MaterialIcons name="group-off" size={30} color={palette.primary} /><Text style={styles.emptyText}>لا توجد دعوات مسجلة لهذه الفعالية.</Text></View>}</View>}</ScrollView></AdminWebShell>;
}

const styles = StyleSheet.create({ page: { paddingBottom: 35 }, back: { alignSelf: "flex-end", flexDirection: "row", gap: 5, alignItems: "center", marginBottom: 12 }, backText: { color: palette.primary, fontSize: 11, fontWeight: "900" }, hero: { borderRadius: 18, minHeight: 112, padding: 19, backgroundColor: "#246B91", flexDirection: "row", gap: 12, alignItems: "center" }, heroTitle: { color: "#FFFFFF", fontSize: 19, fontWeight: "900", textAlign: "right" }, heroCopy: { color: "#D8EFF9", fontSize: 11, marginTop: 5, textAlign: "right" }, title: { color: palette.ink, fontSize: 16, fontWeight: "900", marginTop: 20, textAlign: "right" }, copy: { color: palette.muted, fontSize: 10, lineHeight: 16, textAlign: "right", marginTop: 4 }, list: { marginTop: 12, gap: 9 }, card: { padding: 14, borderRadius: 15, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#DCEAE5" }, cardHead: { flexDirection: "row", gap: 10, alignItems: "center" }, statusDot: { width: 10, height: 10, borderRadius: 5 }, doctor: { color: palette.ink, fontSize: 13, fontWeight: "900", textAlign: "right" }, meta: { color: palette.muted, fontSize: 10, marginTop: 3, textAlign: "right" }, current: { fontSize: 10, fontWeight: "900", marginTop: 5, textAlign: "right" }, statuses: { marginTop: 11, flexDirection: "row-reverse", flexWrap: "wrap", gap: 6 }, status: { minHeight: 31, paddingHorizontal: 8, borderRadius: 8, borderWidth: 1, borderColor: "#D1E0DA", backgroundColor: "#F8FBF9", justifyContent: "center" }, statusText: { color: palette.muted, fontSize: 9, fontWeight: "800" }, note: { minHeight: 52, marginTop: 10, borderRadius: 9, borderWidth: 1, borderColor: "#D1E0DA", backgroundColor: "#F9FCFA", padding: 9, color: palette.ink, fontSize: 10 }, empty: { alignItems: "center", paddingVertical: 36, gap: 7, borderRadius: 15, backgroundColor: "#F7FBF9" }, emptyText: { color: palette.muted, fontSize: 11 }, lock: { minHeight: 350, alignItems: "center", justifyContent: "center", gap: 9 }, lockText: { color: palette.ink, fontSize: 16, fontWeight: "900" } });
