import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { AdminWebShell } from "@/components/admin-web-shell";
import { palette } from "@/components/crm-ui";
import { supabase } from "@/lib/supabase-client";
import { useSupabaseAuth } from "@/lib/supabase-auth";

type Outcome = { id: string; label: string; is_active: boolean; sort_order: number };

export default function AdminOutcomesPage() {
  const { session } = useSupabaseAuth();
  const [outcomes, setOutcomes] = useState<Outcome[]>([]); const [label, setLabel] = useState(""); const [loading, setLoading] = useState(true); const [busyId, setBusyId] = useState<string | null>(null);
  const refresh = useCallback(async () => { if (!supabase || !session) return; setLoading(true); const { data } = await supabase.rpc("tips_crm_list_visit_outcomes"); setOutcomes((data ?? []) as Outcome[]); setLoading(false); }, [session]);
  useEffect(() => { void refresh(); }, [refresh]);
  const save = async () => { const value = label.trim(); if (!supabase || !value) return; setBusyId("new"); const { error } = await supabase.rpc("tips_crm_save_visit_outcome", { outcome_label: value, outcome_sort_order: outcomes.length * 10 + 10 }); setBusyId(null); if (error) { Alert.alert("تعذر الحفظ", "تحقق من صلاحياتك أو من أن الاسم غير مكرر."); return; } setLabel(""); await refresh(); };
  const changeActive = (outcome: Outcome) => Alert.alert(outcome.is_active ? "إلغاء نتيجة زيارة" : "إعادة تفعيل نتيجة", outcome.is_active ? `لن تظهر «${outcome.label}» للمندوبين في الزيارات الجديدة.` : `ستظهر «${outcome.label}» مجدداً للمندوبين.`, [{ text: "رجوع", style: "cancel" }, { text: outcome.is_active ? "إلغاء" : "تفعيل", style: outcome.is_active ? "destructive" : "default", onPress: async () => { if (!supabase) return; setBusyId(outcome.id); const { error } = await supabase.rpc("tips_crm_set_visit_outcome_active", { outcome_id: outcome.id, next_is_active: !outcome.is_active }); setBusyId(null); if (error) { Alert.alert("تعذر التعديل", "يجب أن تبقى نتيجة زيارة واحدة مفعّلة على الأقل."); return; } await refresh(); } }]);
  const activeCount = outcomes.filter((outcome) => outcome.is_active).length;
  return <AdminWebShell title="نتائج الزيارة"><ScrollView contentContainerStyle={styles.page}><View style={styles.hero}><View style={styles.heroIcon}><MaterialIcons name="playlist-add-check" size={23} color="#FFFFFF" /></View><View style={styles.heroCopyWrap}><Text style={styles.heroTitle}>نتائج مخصصة للميدان</Text><Text style={styles.heroCopy}>تحكم بالخيارات التي تظهر للمندوب عند توثيق الزيارة، من دون حذف السجل التاريخي.</Text></View></View><View style={styles.stats}><View style={styles.stat}><Text style={styles.statValue}>{activeCount}</Text><Text style={styles.statLabel}>نتائج فعّالة</Text></View><View style={styles.stat}><Text style={styles.statValue}>{outcomes.length - activeCount}</Text><Text style={styles.statLabel}>نتائج موقوفة</Text></View></View><View style={styles.addCard}><Text style={styles.addTitle}>إضافة نتيجة جديدة</Text><View style={styles.addRow}><TouchableOpacity disabled={busyId === "new"} onPress={() => void save()} style={styles.addButton}><MaterialIcons name="add" size={19} color="#FFFFFF" /><Text style={styles.addButtonText}>{busyId === "new" ? "جارٍ الحفظ…" : "إضافة"}</Text></TouchableOpacity><TextInput value={label} onChangeText={setLabel} placeholder="مثال: تم استلام الطلبية" placeholderTextColor="#93A099" textAlign="right" style={styles.input} returnKeyType="done" onSubmitEditing={() => void save()} /></View></View><Text style={styles.sectionTitle}>الخيارات الحالية</Text>{loading ? <View style={styles.state}><ActivityIndicator color={palette.primary} /></View> : <View style={styles.list}>{outcomes.map((outcome) => <View key={outcome.id} style={styles.row}><TouchableOpacity disabled={busyId === outcome.id} onPress={() => changeActive(outcome)} style={[styles.toggle, outcome.is_active ? styles.toggleActive : styles.toggleInactive]}><MaterialIcons name={outcome.is_active ? "toggle-on" : "toggle-off"} size={28} color={outcome.is_active ? "#0D8068" : "#83918D"} /><Text style={[styles.toggleText, outcome.is_active ? styles.toggleTextActive : undefined]}>{busyId === outcome.id ? "جارٍ الحفظ…" : outcome.is_active ? "فعّالة" : "موقوفة"}</Text></TouchableOpacity><View style={styles.outcomeLabel}><Text style={styles.name}>{outcome.label}</Text><Text style={styles.note}>{outcome.is_active ? "متاحة للفريق الآن" : "محفوظة في السجل السابق فقط"}</Text></View><View style={[styles.icon, { backgroundColor: outcome.is_active ? "#E8F7F1" : "#F2F4F3" }]}><MaterialIcons name={outcome.is_active ? "check-circle" : "pause-circle-outline"} size={20} color={outcome.is_active ? palette.success : palette.muted} /></View></View>)}</View>}</ScrollView></AdminWebShell>;
}

const styles = StyleSheet.create({ page: { paddingBottom: 30 }, hero: { minHeight: 126, padding: 24, borderRadius: 20, backgroundColor: "#143D35", flexDirection: "row", gap: 14, alignItems: "center" }, heroIcon: { width: 47, height: 47, borderRadius: 15, backgroundColor: "#28715F", alignItems: "center", justifyContent: "center" }, heroCopyWrap: { flex: 1, alignItems: "flex-end" }, heroTitle: { color: "#FFFFFF", fontSize: 22, fontWeight: "900", textAlign: "right" }, heroCopy: { color: "#C6E6DD", fontSize: 12, lineHeight: 19, marginTop: 6, textAlign: "right" }, stats: { flexDirection: "row-reverse", gap: 10, marginTop: 16 }, stat: { flex: 1, backgroundColor: "#FFFFFF", borderRadius: 16, borderWidth: 1, borderColor: "#E2EBE7", padding: 15, alignItems: "flex-end" }, statValue: { color: palette.ink, fontSize: 23, fontWeight: "900" }, statLabel: { color: palette.muted, fontSize: 11, marginTop: 4 }, addCard: { backgroundColor: "#FFFFFF", borderRadius: 18, borderWidth: 1, borderColor: "#E2EBE7", padding: 16, marginTop: 16 }, addTitle: { color: palette.ink, fontSize: 14, fontWeight: "900", textAlign: "right", marginBottom: 10 }, addRow: { flexDirection: "row", gap: 9 }, input: { flex: 1, minHeight: 44, borderRadius: 11, borderColor: "#DCE8E3", borderWidth: 1, paddingHorizontal: 12, color: palette.ink, fontSize: 12 }, addButton: { minWidth: 100, borderRadius: 11, backgroundColor: palette.primary, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5 }, addButtonText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" }, sectionTitle: { color: palette.ink, fontSize: 16, fontWeight: "900", textAlign: "right", marginTop: 22, marginBottom: 10 }, state: { minHeight: 130, backgroundColor: "#FFFFFF", borderRadius: 17, alignItems: "center", justifyContent: "center" }, list: { backgroundColor: "#FFFFFF", borderRadius: 18, borderWidth: 1, borderColor: "#E2EBE7", paddingHorizontal: 16 }, row: { minHeight: 75, flexDirection: "row", gap: 12, alignItems: "center", borderBottomWidth: 1, borderBottomColor: "#EDF2F0" }, icon: { width: 39, height: 39, borderRadius: 13, alignItems: "center", justifyContent: "center" }, outcomeLabel: { flex: 1, alignItems: "flex-end" }, name: { color: palette.ink, fontSize: 13, fontWeight: "900", textAlign: "right" }, note: { color: palette.muted, fontSize: 10, marginTop: 4, textAlign: "right" }, toggle: { minWidth: 92, minHeight: 36, borderRadius: 10, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 3 }, toggleActive: { backgroundColor: "#EAF7F2" }, toggleInactive: { backgroundColor: "#F2F4F3" }, toggleText: { color: "#83918D", fontSize: 10, fontWeight: "900" }, toggleTextActive: { color: palette.success } });
